import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'kn' | 'ml' | 'or' | 'pa';

export interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  getCurrentLanguage: () => Language;
  languages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<LanguageCode>('en');

  // Load saved language from localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage') as LanguageCode;
    if (savedLanguage && languages.some(lang => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setCurrentLanguage(lang);
    localStorage.setItem('selectedLanguage', lang);
  };

  const getCurrentLanguage = () => {
    return languages.find(lang => lang.code === currentLanguage) || languages[0];
  };

  // Translation function - for now returns the key, but can be expanded
  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const value: LanguageContextType = {
    currentLanguage,
    setLanguage,
    t,
    getCurrentLanguage,
    languages,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translation strings
export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.soilAnalysis': 'Soil Analysis',
    'nav.diseaseDetection': 'Disease Detection',
    'nav.fertilizerPlans': 'Fertilizer Plans',
    'nav.weather': 'Weather',
    'nav.marketPrices': 'Market Prices',
    'nav.projects': 'Projects',
    'nav.voice': 'Voice',
    'nav.login': 'Login',
    'nav.register': 'Resister',
    
    // Home page
    'home.title': 'Smart Farming with',
    'home.titleAccent': 'AI Technology',
    'home.subtitle': 'Revolutionize your farming with AI-powered soil analysis, disease detection, and crop management. Get expert advice in your local language with voice assistance.',
    'home.startButton': 'Start Farming Smarter',
    'home.demoButton': 'Watch Demo',
    'home.featuresTitle': 'Complete Farming Solution',
    'home.featuresSubtitle': 'From soil testing to harvest management, our AI-powered platform provides comprehensive support for modern farmers in multiple languages.',
    'home.ctaTitle': 'Ready to Transform Your Farming?',
    'home.ctaSubtitle': 'Join thousands of farmers who are already using AI to increase their crop yields and profits.',
    'home.trialButton': 'Start Free Trial',
    'home.supportButton': 'Contact Support',
    'home.demo':'Smart Crop Advisory is an AI-powered platform designed to help farmers improve yield, reduce risks, and make informed decisions. It offers disease detection through image-based diagnosis, soil report analysis to suggest the right crops and fertilizers, and personalized crop recommendations suited for each region. Farmers also receive timely weather alerts to protect their fields and plan irrigation effectively. The system allows farmers to create and maintain projects for each crop, track market prices in real-time, and follow customized fertilizer plans. Together, these features empower farmers to increase productivity, save costs, and get better prices for their produce.'
    ,
    'home.demoVoiceButton':'Hear Demo',
    'home.stopDemoVoiceButton':'Stop Demo',
    // Features
    'feature.soilAnalysis.title': 'Soil Analysis',
    'feature.soilAnalysis.description': 'Upload soil reports and get AI-powered recommendations for optimal crop growth and soil health improvement.',
    'feature.diseaseDetection.title': 'Disease Detection',
    'feature.diseaseDetection.description': 'Snap photos of diseased crops and receive instant diagnosis with treatment recommendations from our AI.',
    'feature.fertilizerPlans.title': 'Fertilizer Plans',
    'feature.fertilizerPlans.description': 'Get personalized fertilizer schedules based on your crop type, growth stage, and soil conditions.',
    'feature.weather.title': 'Weather Guidance',
    'feature.weather.description': 'Real-time weather alerts and farming advice to protect your crops from adverse weather conditions.',
    'feature.marketPrices.title': 'Market Prices',
    'feature.marketPrices.description': 'Track commodity prices and get intelligent insights on the best time to sell your produce.',
    'feature.projects.title': 'Crop Projects',
    'feature.projects.description': 'Manage your farming projects from seed to harvest with comprehensive tracking and reporting.',
    
    // Common
    'common.open': 'Open',
    'common.voice': 'Voice',
    'common.download': 'Download',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Stats
    'stats.farmersHelped': 'Farmers Helped',
    'stats.accuracyRate': 'Accuracy Rate',
    'stats.supportAvailable': 'Support Available',
    
    // Soil Analysis Page
    'soil.title': 'Soil Analysis & Recommendations',
    'soil.subtitle': 'Upload your soil report for AI-powered analysis and recommendations',
    'soil.upload': 'Upload Soil Report',
    'soil.analyze': 'Analyze with AI',
    'soil.recommendations': 'AI Recommendations',
    'soil.generateReport': 'Generate Report',
    'soil.noFile': 'Please upload a soil report first',
    'soil.analyzing': 'Analyzing your soil report...',
    
    // Disease Detection Page
    'disease.title': 'Crop Disease Detection',
    'disease.subtitle': 'Upload images of diseased crops for instant AI diagnosis',
    'disease.upload': 'Upload Crop Image',
    'disease.detect': 'Detect Disease',
    'disease.diagnosis': 'Disease Diagnosis',
    'disease.treatment': 'Treatment Recommendations',
    'disease.noImage': 'Please upload a crop image first',
    'disease.detecting': 'Analyzing crop image...',
    
    // Fertilizer Plans Page
    'fertilizer.title': 'Fertilizer Recommendations',
    'fertilizer.subtitle': 'Get personalized fertilizer plans for your crops',
    'fertilizer.selectCrop': 'Select Crop Type',
    'fertilizer.selectStage': 'Select Growth Stage',
    'fertilizer.getPlan': 'Get Fertilizer Plan',
    'fertilizer.recommendations': 'Fertilizer Recommendations',
    'fertilizer.schedule': 'Application Schedule',
    'fertilizer.selectBoth': 'Please select both crop type and growth stage',
    
    // Weather Page
    'weather.title': 'Weather & Farming Guidance',
    'weather.subtitle': 'Real-time weather updates and farming advice',
    'weather.current': 'Current Weather',
    'weather.forecast': 'Weather Forecast',
    'weather.advice': 'Farming Advice',
    'weather.alerts': 'Weather Alerts',
    
    // Market Prices Page
    'market.title': 'Market Prices & Selling Guide',
    'market.subtitle': 'Track commodity prices and get selling recommendations',
    'market.prices': 'Current Market Prices',
    'market.trends': 'Price Trends',
    'market.recommendations': 'Selling Recommendations',
    'market.selectCrop': 'Select Crop',
    
    // Projects Page
    'projects.title': 'Crop Project Management',
    'projects.subtitle': 'Manage your farming projects from seed to harvest',
    'projects.create': 'Create New Project',
    'projects.active': 'Active Projects',
    'projects.completed': 'Completed Projects',
    'projects.view': 'View Project',
    'projects.edit': 'Edit Project',
    
    // Auth Pages
    'auth.login': 'Login to Your Account',
    'auth.signup': 'Create New Account',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.loginButton': 'Login',
    'auth.signupButton': 'Sign Up',
    'auth.switchToSignup': "Don't have an account? Sign up",
    'auth.switchToLogin': 'Already have an account? Login',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.mobile': 'Mobile Number',
    'auth.location': 'Location',
    'auth.age': 'Age',
    'auth.enterName': 'Enter your full name',
    'auth.enterMobile': 'Enter your mobile number',
    'auth.enterPassword': 'Enter your password',
    'auth.confirmPasswordText': 'Confirm your password',
    'auth.selectLocation': 'Select your location',
    'auth.enterAge': 'Enter your age',
    'auth.selectFarmerType': 'Select farmer type',
    'auth.namePlaceholder': 'Enter your full name',
    'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
    'auth.passwordPlaceholder': 'Enter a strong password',
    'auth.confirmPasswordPlaceholder': 'Re-enter your password',
    'auth.agePlaceholder': 'Enter your age',
    'auth.selectLocationPlaceholder': 'Choose your state',
    'auth.passwordMismatch': 'Passwords do not match!',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.farmerType.label': 'Farmer Type',
    'auth.farmerType.placeholder': 'Select farmer type',
    'auth.farmerType.small': 'Small Farmer',
    'auth.farmerType.marginal': 'Marginal Farmer',
    'auth.farmerType.business': 'Business Farmer',
     'auth.preferredLanguage':'Select Language'
  },
  
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.soilAnalysis': 'मिट्टी विश्लेषण',
    'nav.diseaseDetection': 'रोग की पहचान',
    'nav.fertilizerPlans': 'उर्वरक योजना',
    'nav.weather': 'मौसम',
    'nav.marketPrices': 'बाजार भाव',
    'nav.projects': 'परियोजनाएं',
    'nav.voice': 'आवाज़',
    'nav.login': 'लॉगिन',
    
    // Home page
    'home.title': 'स्मार्ट खेती के साथ',
    'home.titleAccent': 'AI तकनीक',
    'home.subtitle': 'AI-संचालित मिट्टी विश्लेषण, रोग की पहचान और फसल प्रबंधन के साथ अपनी खेती में क्रांति लाएं। अपनी स्थानीय भाषा में आवाज सहायता के साथ विशेषज्ञ सलाह प्राप्त करें।',
    'home.startButton': 'स्मार्ट खेती शुरू करें',
    'home.demoButton': 'डेमो देखें',
    'home.featuresTitle': 'संपूर्ण खेती समाधान',
    'home.featuresSubtitle': 'मिट्टी परीक्षण से लेकर फसल प्रबंधन तक, हमारा AI-संचालित प्लेटफॉर्म कई भाषाओं में आधुनिक किसानों के लिए व्यापक सहायता प्रदान करता है।',
    'home.ctaTitle': 'अपनी खेती को बदलने के लिए तैयार हैं?',
    'home.ctaSubtitle': 'हजारों किसानों के साथ जुड़ें जो अपनी फसल की पैदावार और मुनाफे को बढ़ाने के लिए पहले से ही AI का उपयोग कर रहे हैं।',
    'home.trialButton': 'निःशुल्क परीक्षण शुरू करें',
    'home.supportButton': 'सहायता संपर्क करें',
    'home.demo':'स्मार्ट क्रॉप एडवाइजरी एक एआई-संचालित प्लेटफ़ॉर्म है जो किसानों को पैदावार बढ़ाने, जोखिम कम करने और बेहतर निर्णय लेने में मदद करता है। यह इमेज-बेस्ड डायग्नोसिस से रोग पहचान, मिट्टी रिपोर्ट विश्लेषण से सही फसल और उर्वरक की सिफारिश, और क्षेत्र अनुसार व्यक्तिगत फसल सुझाव प्रदान करता है। किसानों को समय पर मौसम अलर्ट भी मिलते हैं जिससे वे खेतों की रक्षा कर सकें और सिंचाई की योजना सही तरीके से बना सकें। यह प्रणाली किसानों को हर फसल का प्रोजेक्ट बनाने और बनाए रखने, रीयल-टाइम में बाजार भाव देखने और उर्वरक योजना का पालन करने की सुविधा देती है। इन सभी सुविधाओं से किसान उत्पादकता बढ़ा सकते हैं, लागत बचा सकते हैं और बेहतर दाम प्राप्त कर सकते हैं।',
    'home.demoVoiceButton':'डेमो सुनें',
    'home.stopDemoVoiceButton':'डेमो बंद करें',
  
    
    // Features
    'feature.soilAnalysis.title': 'मिट्टी विश्लेषण',
    'feature.soilAnalysis.description': 'मिट्टी की रिपोर्ट अपलोड करें और इष्टतम फसल वृद्धि और मिट्टी स्वास्थ्य सुधार के लिए AI-संचालित सिफारिशें प्राप्त करें।',
    'feature.diseaseDetection.title': 'रोग की पहचान',
    'feature.diseaseDetection.description': 'रोगग्रस्त फसलों की तस्वीरें लें और हमारे AI से तत्काल निदान और उपचार की सिफारिशें प्राप्त करें।',
    'feature.fertilizerPlans.title': 'उर्वरक योजना',
    'feature.fertilizerPlans.description': 'अपनी फसल के प्रकार, वृद्धि चरण और मिट्टी की स्थिति के आधार पर व्यक्तिगत उर्वरक कार्यक्रम प्राप्त करें।',
    'feature.weather.title': 'मौसम मार्गदर्शन',
    'feature.weather.description': 'प्रतिकूल मौसम की स्थिति से अपनी फसलों की सुरक्षा के लिए रीयल-टाइम मौसम अलर्ट और खेती की सलाह।',
    'feature.marketPrices.title': 'बाजार भाव',
    'feature.marketPrices.description': 'कमोडिटी की कीमतों को ट्रैक करें और अपनी उपज को बेचने का सबसे अच्छा समय जानने के लिए बुद्धिमान अंतर्दृष्टि प्राप्त करें।',
    'feature.projects.title': 'फसल परियोजनाएं',
    'feature.projects.description': 'व्यापक ट्रैकिंग और रिपोर्टिंग के साथ बीज से फसल तक अपनी खेती परियोजनाओं का प्रबंधन करें।',
    
    // Common
    'common.open': 'खोलें',
    'common.voice': 'आवाज़',
    'common.download': 'डाउनलोड',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    
    // Stats
    'stats.farmersHelped': 'किसानों की मदद की',
    'stats.accuracyRate': 'सटीकता दर',
    'stats.supportAvailable': 'सहायता उपलब्ध',
    
    // Soil Analysis Page
    'soil.title': 'मिट्टी विश्लेषण और सिफारिशें',
    'soil.subtitle': 'AI-संचालित विश्लेषण और सिफारिशों के लिए अपनी मिट्टी की रिपोर्ट अपलोड करें',
    'soil.upload': 'मिट्टी रिपोर्ट अपलोड करें',
    'soil.analyze': 'AI के साथ विश्लेषण करें',
    'soil.recommendations': 'AI सिफारिशें',
    'soil.generateReport': 'रिपोर्ट तैयार करें',
    'soil.noFile': 'कृपया पहले मिट्टी की रिपोर्ट अपलोड करें',
    'soil.analyzing': 'आपकी मिट्टी की रिपोर्ट का विश्लेषण कर रहे हैं...',
    
    // Disease Detection Page
    'disease.title': 'फसल रोग की पहचान',
    'disease.subtitle': 'तत्काल AI निदान के लिए रोगग्रस्त फसलों की तस्वीरें अपलोड करें',
    'disease.upload': 'फसल की तस्वीर अपलोड करें',
    'disease.detect': 'रोग की पहचान करें',
    'disease.diagnosis': 'रोग निदान',
    'disease.treatment': 'उपचार की सिफारिशें',
    'disease.noImage': 'कृपया पहले फसल की तस्वीर अपलोड करें',
    'disease.detecting': 'फसल की तस्वीर का विश्लेषण कर रहे हैं...',
    
    // Fertilizer Plans Page
    'fertilizer.title': 'उर्वरक सिफारिशें',
    'fertilizer.subtitle': 'अपनी फसलों के लिए व्यक्तिगत उर्वरक योजना प्राप्त करें',
    'fertilizer.selectCrop': 'फसल का प्रकार चुनें',
    'fertilizer.selectStage': 'वृद्धि चरण चुनें',
    'fertilizer.getPlan': 'उर्वरक योजना प्राप्त करें',
    'fertilizer.recommendations': 'उर्वरक सिफारिशें',
    'fertilizer.schedule': 'प्रयोग कार्यक्रम',
    'fertilizer.selectBoth': 'कृपया फसल का प्रकार और वृद्धि चरण दोनों चुनें',
    
    // Weather Page
    'weather.title': 'मौसम और खेती मार्गदर्शन',
    'weather.subtitle': 'रीयल-टाइम मौसम अपडेट और खेती की सलाह',
    'weather.current': 'वर्तमान मौसम',
    'weather.forecast': 'मौसम पूर्वानुमान',
    'weather.advice': 'खेती की सलाह',
    'weather.alerts': 'मौसम चेतावनी',
    
    // Market Prices Page
    'market.title': 'बाजार भाव और बिक्री गाइड',
    'market.subtitle': 'कमोडिटी की कीमतों को ट्रैक करें और बिक्री की सिफारिशें प्राप्त करें',
    'market.prices': 'वर्तमान बाजार भाव',
    'market.trends': 'मूल्य रुझान',
    'market.recommendations': 'बिक्री सिफारिशें',
    'market.selectCrop': 'फसल चुनें',
    
    // Projects Page
    'projects.title': 'फसल परियोजना प्रबंधन',
    'projects.subtitle': 'बीज से फसल तक अपनी खेती परियोजनाओं का प्रबंधन करें',
    'projects.create': 'नई परियोजना बनाएं',
    'projects.active': 'सक्रिय परियोजनाएं',
    'projects.completed': 'पूर्ण परियोजनाएं',
    'projects.view': 'परियोजना देखें',
    'projects.edit': 'परियोजना संपादित करें',
    
    // Auth Pages
    'auth.login': 'अपने खाते में लॉगिन करें',
    'auth.signup': 'नया खाता बनाएं',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.name': 'पूरा नाम',
    'auth.phone': 'फोन नंबर',
    'auth.loginButton': 'लॉगिन',
    'auth.signupButton': 'साइन अप',
    'auth.switchToSignup': 'क्या आपका कोई खाता नहीं है? साइन अप करें',
    'auth.switchToLogin': 'क्या आपका पहले से खाता है? लॉगिन करें',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.mobile': 'मोबाइल नंबर',
    'auth.location': 'स्थान',
    'auth.age': 'उम्र',
    'auth.enterName': 'अपना पूरा नाम दर्ज करें',
    'auth.enterMobile': 'अपना मोबाइल नंबर दर्ज करें',
    'auth.enterPassword': 'अपना पासवर्ड दर्ज करें',
    'auth.confirmPasswordText': 'अपने पासवर्ड की पुष्टि करें',
    'auth.selectLocation': 'अपना स्थान चुनें',
    'auth.enterAge': 'अपनी उम्र दर्ज करें',
    'auth.selectFarmerType': 'किसान का प्रकार चुनें',
    'auth.namePlaceholder': 'अपना पूरा नाम दर्ज करें',
    'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
    'auth.passwordPlaceholder': 'एक मजबूत पासवर्ड दर्ज करें',
    'auth.confirmPasswordPlaceholder': 'अपना पासवर्ड फिर से दर्ज करें',
    'auth.agePlaceholder': 'अपनी उम्र दर्ज करें',
    'auth.selectLocationPlaceholder': 'अपना राज्य चुनें',
    'auth.passwordMismatch': 'पासवर्ड मेल नहीं खाते!',
    'auth.dontHaveAccount': 'खाता नहीं है?',
    'auth.alreadyHaveAccount': 'पहले से खाता है?',
    'auth.farmerType.label': 'किसान का प्रकार',
    'auth.farmerType.placeholder': 'किसान का प्रकार चुनें',
    'auth.farmerType.small': 'छोटा किसान',
    'auth.farmerType.marginal': 'सीमांत किसान',
    'auth.farmerType.business': 'व्यापारिक किसान',
  },
  
  bn: {
    // Navigation
    'nav.home': 'হোম',
    'nav.soilAnalysis': 'মাটি বিশ্লেষণ',
    'nav.diseaseDetection': 'রোগ শনাক্তকরণ',
    'nav.fertilizerPlans': 'সার পরিকল্পনা',
    'nav.weather': 'আবহাওয়া',
    'nav.marketPrices': 'বাজার দর',
    'nav.projects': 'প্রকল্প',
    'nav.voice': 'ভয়েস',
    'nav.login': 'লগইন',
    
    // Home page
    'home.title': 'স্মার্ট কৃষিকাজ',
    'home.titleAccent': 'AI প্রযুক্তি',
    'home.subtitle': 'AI-চালিত মাটি বিশ্লেষণ, রোগ শনাক্তকরণ এবং ফসল ব্যবস্থাপনার মাধ্যমে আপনার কৃষিকাজে বিপ্লব আনুন। আপনার স্থানীয় ভাষায় ভয়েস সহায়তায় বিশেষজ্ঞ পরামর্শ পান।',
    'home.startButton': 'স্মার্ট কৃষি শুরু করুন',
    'home.demoButton': 'ডেমো দেখুন',
    'home.featuresTitle': 'সম্পূর্ণ কৃষি সমাধান',
    'home.featuresSubtitle': 'মাটি পরীক্ষা থেকে ফসল ব্যবস্থাপনা পর্যন্ত, আমাদের AI-চালিত প্ল্যাটফর্ম আধুনিক কৃষকদের জন্য বহু ভাষায় বিস্তৃত সহায়তা প্রদান করে।',
    'home.ctaTitle': 'আপনার কৃষিকাজ পরিবর্তন করতে প্রস্তুত?',
    'home.ctaSubtitle': 'হাজার হাজার কৃষক ইতিমধ্যে AI ব্যবহার করে তাদের ফসলের উৎপাদন এবং লাভ বাড়াচ্ছেন।',
    'home.trialButton': 'বিনামূল্যে ট্রায়াল শুরু করুন',
    'home.supportButton': 'সহায়তা যোগাযোগ করুন',
    'home.demo':'স্মার্ট ক্রপ অ্যাডভাইজরি একটি এআই-চালিত প্ল্যাটফর্ম যা কৃষকদের ফলন বাড়াতে, ঝুঁকি কমাতে এবং সঠিক সিদ্ধান্ত নিতে সহায়তা করে। এটি ইমেজ-ভিত্তিক রোগ শনাক্তকরণ, মাটির রিপোর্ট বিশ্লেষণ করে সঠিক ফসল ও সার প্রস্তাব করে, এবং প্রতিটি অঞ্চলের জন্য ব্যক্তিগত ফসল সুপারিশ প্রদান করে। কৃষকরা সময়মতো আবহাওয়ার সতর্কবার্তাও পান যাতে তারা ফসল রক্ষা করতে ও সেচের পরিকল্পনা করতে পারেন। এই সিস্টেম কৃষকদের প্রতিটি ফসলের জন্য প্রকল্প তৈরি ও বজায় রাখা, রিয়েল-টাইম বাজারমূল্য ট্র্যাক করা এবং সার পরিকল্পনা অনুসরণ করার সুযোগ দেয়। সব মিলিয়ে, এই বৈশিষ্ট্যগুলি কৃষকদের উৎপাদনশীলতা বাড়াতে, খরচ কমাতে এবং ভালো দাম পেতে সাহায্য করে।',
    'home.demoVoiceButton':'ডেমো শুনুন',
    'home.stopDemoVoiceButton':'ডেমো বন্ধ করুন',
    // Features
    'feature.soilAnalysis.title': 'মাটি বিশ্লেষণ',
    'feature.soilAnalysis.description': 'মাটি রিপোর্ট আপলোড করুন এবং সর্বোত্তম ফসল বৃদ্ধির জন্য AI-চালিত সুপারিশ পান।',
    'feature.diseaseDetection.title': 'রোগ শনাক্তকরণ',
    'feature.diseaseDetection.description': 'রোগগ্রস্ত ফসলের ছবি তুলে আমাদের AI থেকে তাত্ক্ষণিক রোগ নির্ণয় এবং চিকিৎসার সুপারিশ পান।',
    'feature.fertilizerPlans.title': 'সার পরিকল্পনা',
    'feature.fertilizerPlans.description': 'আপনার ফসলের প্রকার, বৃদ্ধির স্তর এবং মাটির অবস্থার উপর ভিত্তি করে ব্যক্তিগত সার সময়সূচী পান।',
    'feature.weather.title': 'আবহাওয়া নির্দেশিকা',
    'feature.weather.description': 'অবাঞ্ছিত আবহাওয়া থেকে আপনার ফসলকে রক্ষা করার জন্য রিয়েল-টাইম আবহাওয়ার সতর্কতা এবং কৃষি পরামর্শ পান।',
    'feature.marketPrices.title': 'বাজার দর',
    'feature.marketPrices.description': 'পণ্যের দাম ট্র্যাক করুন এবং আপনার উৎপাদন বিক্রির জন্য সেরা সময় সম্পর্কে বুদ্ধিমান অন্তর্দৃষ্টি পান।',
    'feature.projects.title': 'ফসল প্রকল্প',
    'feature.projects.description': 'বীজ থেকে শুরু করে ফসল তোলা পর্যন্ত আপনার কৃষি প্রকল্পগুলি পরিচালনা করুন।',
    
    // Common
    'common.open': 'খোলুন',
    'common.voice': 'ভয়েস',
    'common.download': 'ডাউনলোড',
    'common.save': 'সংরক্ষণ করুন',
    'common.cancel': 'বাতিল করুন',
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'ত্রুটি',
    'common.success': 'সাফল্য',
    
    // Stats
    'stats.farmersHelped': 'কৃষকদের সাহায্য করা হয়েছে',
    'stats.accuracyRate': 'সঠিকতার হার',
    'stats.supportAvailable': 'সহায়তা উপলব্ধ',
    
    // Soil Analysis Page
    'soil.title': 'মাটি বিশ্লেষণ ও সুপারিশ',
    'soil.subtitle': 'AI-চালিত বিশ্লেষণ এবং সুপারিশের জন্য আপনার মাটি রিপোর্ট আপলোড করুন',
    'soil.upload': 'মাটি রিপোর্ট আপলোড করুন',
    'soil.analyze': 'AI দিয়ে বিশ্লেষণ করুন',
    'soil.recommendations': 'AI সুপারিশ',
    'soil.generateReport': 'রিপোর্ট তৈরি করুন',
    'soil.noFile': 'দয়া করে প্রথমে একটি মাটি রিপোর্ট আপলোড করুন',
    'soil.analyzing': 'আপনার মাটি রিপোর্ট বিশ্লেষণ করা হচ্ছে...',
    
    // Disease Detection Page
    'disease.title': 'ফসল রোগ শনাক্তকরণ',
    'disease.subtitle': 'তাত্ক্ষণিক AI রোগ নির্ণয়ের জন্য রোগগ্রস্ত ফসলের ছবি আপলোড করুন',
    'disease.upload': 'ফসলের ছবি আপলোড করুন',
    'disease.detect': 'রোগ শনাক্ত করুন',
    'disease.diagnosis': 'রোগ নির্ণয়',
    'disease.treatment': 'চিকিৎসার সুপারিশ',
    'disease.noImage': 'দয়া করে প্রথমে একটি ফসলের ছবি আপলোড করুন',
    'disease.detecting': 'ফসলের ছবি বিশ্লেষণ করা হচ্ছে...',
    
    // Fertilizer Plans Page
    'fertilizer.title': 'সার সুপারিশ',
    'fertilizer.subtitle': 'আপনার ফসলের জন্য ব্যক্তিগত সার পরিকল্পনা পান',
    'fertilizer.selectCrop': 'ফসলের প্রকার নির্বাচন করুন',
    'fertilizer.selectStage': 'বৃদ্ধির স্তর নির্বাচন করুন',
    'fertilizer.getPlan': 'সার পরিকল্পনা পান',
    'fertilizer.recommendations': 'সার সুপারিশ',
    'fertilizer.schedule': 'প্রয়োগ সময়সূচী',
    'fertilizer.selectBoth': 'দয়া করে উভয় ফসলের প্রকার এবং বৃদ্ধির স্তর নির্বাচন করুন',
    
    // Weather Page
    'weather.title': 'আবহাওয়া ও কৃষি নির্দেশিকা',
    'weather.subtitle': 'রিয়েল-টাইম আবহাওয়া আপডেট এবং কৃষি পরামর্শ',
    'weather.current': 'বর্তমান আবহাওয়া',
    'weather.forecast': 'আবহাওয়ার পূর্বাভাস',
    'weather.advice': 'কৃষি পরামর্শ',
    'weather.alerts': 'আবহাওয়ার সতর্কতা',
    
    // Market Prices Page
    'market.title': 'বাজার দর ও বিক্রয় গাইড',
    'market.subtitle': 'পণ্যের দাম ট্র্যাক করুন এবং বিক্রয়ের জন্য সুপারিশ পান',
    'market.prices': 'বর্তমান বাজার দর',
    'market.trends': 'দামের প্রবণতা',
    'market.recommendations': 'বিক্রয়ের সুপারিশ',
    'market.selectCrop': 'ফসল নির্বাচন করুন',
    
    // Projects Page
    'projects.title': 'ফসল প্রকল্প ব্যবস্থাপনা',
    'projects.subtitle': 'বীজ থেকে ফসল তোলা পর্যন্ত আপনার কৃষি প্রকল্পগুলি পরিচালনা করুন',
    'projects.create': 'নতুন প্রকল্প তৈরি করুন',
    'projects.active': 'সক্রিয় প্রকল্প',
    'projects.completed': 'সম্পন্ন প্রকল্প',
    'projects.view': 'প্রকল্প দেখুন',
    'projects.edit': 'প্রকল্প সম্পাদনা করুন',
    
    // Auth Pages
    'auth.login': 'আপনার অ্যাকাউন্টে লগইন করুন',
    'auth.signup': 'নতুন অ্যাকাউন্ট তৈরি করুন',
    'auth.email': 'ইমেইল ঠিকানা',
    'auth.password': 'পাসওয়ার্ড',
    'auth.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'auth.name': 'পুরো নাম',
    'auth.phone': 'ফোন নম্বর',
    'auth.loginButton': 'লগইন',
    'auth.signupButton': 'সাইন আপ',
    'auth.switchToSignup': 'একটি অ্যাকাউন্ট নেই? সাইন আপ করুন',
    'auth.switchToLogin': 'Already have an account? Login',
    'auth.forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.mobile': 'মোবাইল নম্বর',
    'auth.location': 'অবস্থান',
    'auth.age': 'বয়স',
    'auth.enterName': 'আপনার পুরো নাম লিখুন',
    'auth.enterMobile': 'আপনার মোবাইল নম্বর লিখুন',
    'auth.enterPassword': 'আপনার পাসওয়ার্ড লিখুন',
    'auth.confirmPasswordText': 'আপনার পাসওয়ার্ড নিশ্চিত করুন',
    'auth.selectLocation': 'আপনার অবস্থান নির্বাচন করুন',
    'auth.enterAge': 'আপনার বয়স লিখুন',
    'auth.selectFarmerType': 'কৃষকের প্রকার নির্বাচন করুন',
    'auth.namePlaceholder': 'আপনার পুরো নাম লিখুন',
    'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
    'auth.passwordPlaceholder': 'একটি শক্তিশালী পাসওয়ার্ড লিখুন',
    'auth.confirmPasswordPlaceholder': 'আপনার পাসওয়ার্ড আবার লিখুন',
    'auth.agePlaceholder': 'আপনার বয়স লিখুন',
    'auth.selectLocationPlaceholder': 'আপনার রাজ্য নির্বাচন করুন',
    'auth.passwordMismatch': 'পাসওয়ার্ড মেলে না!',
    'auth.dontHaveAccount': 'একটি অ্যাকাউন্ট নেই?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.farmerType.label': 'কৃষকের প্রকার',
    'auth.farmerType.placeholder': 'কৃষকের প্রকার নির্বাচন করুন',
    'auth.farmerType.small': 'ছোট কৃষক',
    'auth.farmerType.marginal': 'সীমান্ত কৃষক',
    'auth.farmerType.business': 'ব্যবসায়ী কৃষক',
  },
  
  te: {
    // Navigation
    'nav.home': 'హోమ్',
    'nav.soilAnalysis': 'మట్టి విశ్లేషణ',
    'nav.diseaseDetection': 'రోగ గుర్తింపు',
    'nav.fertilizerPlans': 'ఎరువుల ప్రణాళికలు',
    'nav.weather': 'వాతావరణం',
    'nav.marketPrices': 'మార్కెట్ ధరలు',
    'nav.projects': 'ప్రాజెక్టులు',
    'nav.voice': 'వాయిస్',
    'nav.login': 'లాగిన్',
    
    // Home page
    'home.title': 'స్మార్ట్ వ్యవసాయం',
    'home.titleAccent': 'AI సాంకేతికత',
    'home.subtitle': 'AI ఆధారిత మట్టి విశ్లేషణ, రోగ గుర్తింపు మరియు పంట నిర్వహణతో మీ వ్యవసాయాన్ని విప్లవాత్మకంగా మార్చుకోండి. మీ స్థానిక భాషలో వాయిస్ సహాయంతో నిపుణుల సలహా పొందండి.',
    'home.startButton': 'స్మార్ట్ వ్యవసాయం ప్రారంభించండి',
    'home.demoButton': 'డెమో చూడండి',
    'home.featuresTitle': 'పూర్తి వ్యవసాయ పరిష్కారం',
    'home.featuresSubtitle': 'మట్టి పరీక్ష నుండి పంట నిర్వహణ వరకు, మా AI ఆధారిత ప్లాట్‌ఫారమ్ ఆధునిక రైతులకు అనేక భాషల్లో సమగ్ర సహాయాన్ని అందిస్తుంది.',
    'home.ctaTitle': 'మీ వ్యవసాయాన్ని మార్చడానికి సిద్ధంగా ఉన్నారా?',
    'home.ctaSubtitle': 'వెయ్యి మంది రైతులు ఇప్పటికే AI ఉపయోగించి తమ పంట దిగుబడులు మరియు లాభాలను పెంచుతున్నారు.',
    'home.trialButton': 'ఉచిత ట్రయల్ ప్రారంభించండి',
    'home.supportButton': 'సహాయం కోసం సంప్రదించండి',
    'home.demo':'స్మార్ట్ క్రాప్ అడ్వైజరీ అనేది రైతులు దిగుబడిని పెంచుకోవడంలో, ప్రమాదాలను తగ్గించుకోవడంలో మరియు సరైన నిర్ణయాలు తీసుకోవడంలో సహాయపడే AI ఆధారిత వేదిక. ఇది ఇమేజ్ ఆధారిత వ్యాధి గుర్తింపు, మట్టిపరీక్షల విశ్లేషణ ద్వారా సరైన పంటలు, ఎరువులు సూచనలు, మరియు ప్రతి ప్రాంతానికి ప్రత్యేకమైన పంటల సిఫారసులు ఇస్తుంది. రైతులకు సమయానుసార వాతావరణ హెచ్చరికలు లభిస్తాయి, తద్వారా పంటలను రక్షించుకోవచ్చు మరియు నీటి పారుదల ప్రణాళికను రూపొందించుకోవచ్చు. ఈ సిస్టమ్ రైతులు ప్రతి పంటకు ప్రాజెక్ట్ సృష్టించి నిర్వహించుకోవడం, రియల్-టైమ్ మార్కెట్ ధరలు తెలుసుకోవడం, ఎరువుల ప్రణాళిక అనుసరించడం వంటి సౌకర్యాలు ఇస్తుంది. ఇవన్నీ కలిపి రైతులు ఉత్పాదకత పెంచుకోవడంలో, ఖర్చులు తగ్గించుకోవడంలో మరియు మంచి ధర పొందడంలో సహాయపడతాయి.',
    'home.domobutton':'డెమో వినండి',
    'home.stopDemoVoiceButton':'డెమో ఆపు',
    // Features
    'feature.soilAnalysis.title': 'మట్టి విశ్లేషణ',
    'feature.soilAnalysis.description': 'మట్టి నివేదికలను అప్లోడ్ చేసి, పంట యొక్క ఆప్టిమల్ వృద్ధి మరియు మట్టి ఆరోగ్యాన్ని మెరుగుపరచడానికి AI ఆధారిత సిఫార్సులను పొందండి.',
    'feature.diseaseDetection.title': 'రోగ గుర్తింపు',
    'feature.diseaseDetection.description': 'రోగగ్రస్త పంటల ఫోటోలు తీసి, మా AI ద్వారా తక్షణ నిర్ధారణ మరియు చికిత్స సిఫారసులను పొందండి.',
    'feature.fertilizerPlans.title': 'ఎరువుల ప్రణాళికలు',
    'feature.fertilizerPlans.description': 'మీ పంట యొక్క రకం, వృద్ధి దశ మరియు మట్టి పరిస్థితుల ఆధారంగా వ్యక్తిగత ఎరువుల షెడ్యూల్ పొందండి.',
    'feature.weather.title': 'వాతావరణ మార్గదర్శనం',
    'feature.weather.description': 'అవసరమైన వాతావరణ పరిస్థితుల నుండి మీ పంటలను కాపాడటానికి రియల్-టైమ్ వాతావరణ హెచ్చరికలు మరియు వ్యవసాయ సలహాలు.',
    'feature.marketPrices.title': 'మార్కెట్ ధరలు',
    'feature.marketPrices.description': 'వాణిజ్య ధరలను ట్రాక్ చేయండి మరియు మీ ఉత్పత్తిని అమ్మడానికి ఉత్తమ సమయం గురించి తెలివైన అవగాహన పొందండి.',
    'feature.projects.title': 'క్రాప్ ప్రాజెక్టులు',
    'feature.projects.description': 'విత్తనం నుండి కూరగాయల వరకు మీ వ్యవసాయ ప్రాజెక్టులను నిర్వహించండి.',
    
    // Common
    'common.open': 'తిరిగి రా',
    'common.voice': 'వాయిస్',
    'common.download': 'డౌన్‌లోడ్',
    'common.save': 'సేవ్',
    'common.cancel': 'రద్దు చేయండి',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.error': 'లోపం',
    'common.success': 'విజయం',
    
    // Stats
    'stats.farmersHelped': 'కార్యకర్తలు సహాయపడిన',
    'stats.accuracyRate': 'సరిగ్గా రేటు',
    'stats.supportAvailable': 'సహాయం అందుబాటులో ఉంది',
    
    // Soil Analysis Page
    'soil.title': 'మట్టి విశ్లేషణ & సిఫారసులు',
    'soil.subtitle': 'AI ఆధారిత విశ్లేషణ మరియు సిఫారసుల కోసం మీ మట్టి నివేదికను అప్లోడ్ చేయండి',
    'soil.upload': 'మట్టి నివేదికను అప్లోడ్ చేయండి',
    'soil.analyze': 'AI తో విశ్లేషించండి',
    'soil.recommendations': 'AI సిఫారసులు',
    'soil.generateReport': 'రిపోర్ట్ రూపొందించండి',
    'soil.noFile': 'దయచేసి ముందుగా ఒక మట్టి నివేదికను అప్లోడ్ చేయండి',
    'soil.analyzing': 'మీ మట్టి నివేదికను విశ్లేషించడం జరుగుతోంది...',
    
    // Disease Detection Page
    'disease.title': 'క్రాప్ డిసీజ్ డిటెక్షన్',
    'disease.subtitle': 'తక్షణ AI నిర్ధారణ కోసం రోగగ్రస్త పంటల చిత్రాలను అప్లోడ్ చేయండి',
    'disease.upload': 'క్రాప్ ఇమేజ్‌ను అప్లోడ్ చేయండి',
    'disease.detect': 'రోగాన్ని గుర్తించండి',
    'disease.diagnosis': 'రోగ నిర్ధారణ',
    'disease.treatment': 'చికిత్స సిఫారసులు',
    'disease.noImage': 'దయచేసి ముందుగా ఒక పంట చిత్రాన్ని అప్లోడ్ చేయండి',
    'disease.detecting': 'పంట చిత్రాన్ని విశ్లేషించడం జరుగుతోంది...',
    
    // Fertilizer Plans Page
    'fertilizer.title': 'ఎరువుల సిఫారసులు',
    'fertilizer.subtitle': 'మీ పంటలకు వ్యక్తిగత ఎరువుల ప్రణాళికలను పొందండి',
    'fertilizer.selectCrop': 'పంట రకాన్ని ఎంచుకోండి',
    'fertilizer.selectStage': 'వృద్ధి దశను ఎంచుకోండి',
    'fertilizer.getPlan': 'ఎరువుల ప్రణాళిక పొందండి',
    'fertilizer.recommendations': 'ఎరువుల సిఫారసులు',
    'fertilizer.schedule': 'అప్లికేషన్ షెడ్యూల్',
    'fertilizer.selectBoth': 'దయచేసి పంట రకం మరియు వృద్ధి దశను రెండూ ఎంచుకోండి',
    
    // Weather Page
    'weather.title': 'వాతావరణం & వ్యవసాయ మార్గదర్శనం',
    'weather.subtitle': 'రియల్-టైమ్ వాతావరణ నవీకరణలు మరియు వ్యవసాయ సలహాలు',
    'weather.current': 'ప్రస్తుత వాతావరణం',
    'weather.forecast': 'వాతావరణం అంచనా',
    'weather.advice': 'వ్యవసాయ సలహా',
    'weather.alerts': 'వాతావరణ హెచ్చరికలు',
    
    // Market Prices Page
    'market.title': 'మార్కెట్ ధరలు & అమ్మకాల గైడ్',
    'market.subtitle': 'వాణిజ్య ధరలను ట్రాక్ చేయండి మరియు అమ్మకానికి సిఫారసులు పొందండి',
    'market.prices': 'ప్రస్తుత మార్కెట్ ధరలు',
    'market.trends': 'ధరల ధోరణులు',
    'market.recommendations': 'అమ్మకాల సిఫారసులు',
    'market.selectCrop': 'పంటను ఎంచుకోండి',
    
    // Projects Page
    'projects.title': 'క్రాప్ ప్రాజెక్ట్ నిర్వహణ',
    'projects.subtitle': 'విత్తనం నుండి కూరగాయల వరకు మీ వ్యవసాయ ప్రాజెక్టులను నిర్వహించండి',
    'projects.create': 'కొత్త ప్రాజెక్ట్ సృష్టించండి',
    'projects.active': 'సక్రియమైన ప్రాజెక్టులు',
    'projects.completed': 'పూర్తి అయిన ప్రాజెక్టులు',
    'projects.view': 'ప్రాజెక్ట్ చూడండి',
    'projects.edit': 'ప్రాజెక్ట్ సవరించండి',
    
    // Auth Pages
    'auth.login': 'మీ ఖాతాలో లాగిన్ చేయండి',
    'auth.signup': 'కొత్త ఖాతా సృష్టించండి',
    'auth.email': 'ఇమెయిల్ చిరునామా',
    'auth.password': 'పాస్వర్డ్',
    'auth.confirmPassword': 'పాస్వర్డ్ నిర్ధారించండి',
    'auth.name': 'పూర్తి పేరు',
    'auth.phone': 'ఫోన్ నంబర్',
    'auth.loginButton': 'లాగిన్',
    'auth.signupButton': 'సైన్ అప్',
    'auth.switchToSignup': 'ఖాతా లేదు? సైన్ అప్ చేయండి',
    'auth.switchToLogin': 'Already have an account? Login',
    'auth.forgotPassword': 'పాస్వర్డ్ మర్చిపోయారా?',
    'auth.mobile': 'మొబైల్ నంబర్',
    'auth.location': 'ప్రదేశం',
    'auth.age': 'వయస్సు',
    'auth.enterName': 'మీ పూర్తి పేరు నమోదు చేయండి',
    'auth.enterMobile': 'మీ మొబైల్ నంబర్ నమోదు చేయండి',
    'auth.enterPassword': 'మీ పాస్వర్డ్ నమోదు చేయండి',
    'auth.confirmPasswordText': 'మీ పాస్వర్డ్ నిర్ధారించండి',
    'auth.selectLocation': 'మీ ప్రదేశం ఎంచుకోండి',
    'auth.enterAge': 'మీ వయస్సు నమోదు చేయండి',
    'auth.selectFarmerType': 'కార్యకర్త రకం ఎంచుకోండి',
    'auth.namePlaceholder': 'మీ పూర్తి పేరు నమోదు చేయండి',
    'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
    'auth.passwordPlaceholder': 'ఒక బలమైన పాస్వర్డ్ నమోదు చేయండి',
    'auth.confirmPasswordPlaceholder': 'మీ పాస్వర్డ్ మళ్లీ నమోదు చేయండి',
    'auth.agePlaceholder': 'మీ వయస్సు నమోదు చేయండి',
    'auth.selectLocationPlaceholder': 'మీ రాష్ట్రం ఎంచుకోండి',
    'auth.passwordMismatch': 'పాస్వర్డ్‌లు సరిపోలడం లేదు!',
    'auth.dontHaveAccount': 'ఒక ఖాతా లేదు?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.farmerType.label': 'కార్యకర్త రకం',
    'auth.farmerType.placeholder': 'కార్యకర్త రకం ఎంచుకోండి',
    'auth.farmerType.small': 'చిన్న రైతు',
    'auth.farmerType.marginal': 'సరిహద్దు రైతు',
    'auth.farmerType.business': 'వ్యాపార రైతు',
  },
  
  mr: {
    // Navigation
    'nav.home': 'होम',
    'nav.soilAnalysis': 'माती विश्लेषण',
    'nav.diseaseDetection': 'रोग ओळख',
    'nav.fertilizerPlans': 'खत योजना',
    'nav.weather': 'हवामान',
    'nav.marketPrices': 'बाजार भाव',
    'nav.projects': 'प्रकल्प',
    'nav.voice': 'आवाज',
    'nav.login': 'लॉगिन',
    
    // Home page
    'home.title': 'स्मार्ट शेती',
    'home.titleAccent': 'AI तंत्रज्ञान',
    'home.subtitle': 'AI-संचालित माती विश्लेषण, रोग ओळख आणि पिक व्यवस्थापनासह आपल्या शेतीत क्रांती घडवा. आपल्या स्थानिक भाषेत आवाज सहाय्याने तज्ज्ञ सल्ला मिळवा.',
    'home.startButton': 'स्मार्ट शेती सुरू करा',
    'home.demoButton': 'डेमो पहा',
    'home.featuresTitle': 'पूर्ण शेती समाधान',
    'home.featuresSubtitle': 'माती तपासणीपासून पिक व्यवस्थापनापर्यंत, आमचे AI-संचालित प्लॅटफॉर्म आधुनिक शेतकऱ्यांसाठी अनेक भाषांमध्ये व्यापक सहाय्य प्रदान करते.',
    'home.ctaTitle': 'आपली शेती बदलण्यासाठी तयार आहात?',
    'home.ctaSubtitle': 'हजारो शेतकरी आधीच AI वापरून त्यांच्या पिकांचे उत्पादन आणि नफा वाढवत आहेत.',
    'home.trialButton': 'मोफत ट्रायल सुरू करा',
    'home.supportButton': 'सहाय्यासाठी संपर्क करा',
    'home.demo':'स्मार्ट क्रॉप अॅडव्हायझरी हे एआय-आधारित व्यासपीठ आहे जे शेतकऱ्यांना उत्पादन वाढवण्यासाठी, जोखीम कमी करण्यासाठी आणि योग्य निर्णय घेण्यासाठी मदत करते. हे इमेज-बेस्ड रोग निदान, माती अहवाल विश्लेषणातून योग्य पिके आणि खतांची शिफारस, तसेच क्षेत्रानुसार वैयक्तिकृत पिकांच्या शिफारसी देते. शेतकऱ्यांना वेळेवर हवामान अलर्ट मिळतात ज्यामुळे ते शेतांचे संरक्षण करू शकतात आणि सिंचनाची योग्य योजना करू शकतात. ही प्रणाली शेतकऱ्यांना प्रत्येक पिकासाठी प्रकल्प तयार व जतन करण्याची, रिअल-टाइम बाजारभाव जाणून घेण्याची आणि खतांच्या योजनेचे पालन करण्याची सुविधा देते. या सर्व सुविधांमुळे शेतकरी उत्पादन वाढवू शकतात, खर्च वाचवू शकतात आणि अधिक चांगला दर मिळवू शकतात',
    'home.domobutton':'डेमो ऐका',
    'home.stopDemoVoiceButton':'डेमो थांबवा',
    // Features
    'feature.soilAnalysis.title': 'माती विश्लेषण',
    'feature.soilAnalysis.description': 'मातीच्या रिपोर्ट्स अपलोड करा आणि अनुकूल पिक वाढ आणि मातीच्या आरोग्य सुधारण्यासाठी AI-संचालित शिफारसी मिळवा.',
    'feature.diseaseDetection.title': 'रोग ओळख',
    'feature.diseaseDetection.description': 'रोगग्रस्त पिकांचे फोटो काढा आणि आमच्या AI कडून तात्काळ निदान आणि उपचाराच्या शिफारसी मिळवा.',
    'feature.fertilizerPlans.title': 'खत योजना',
    'feature.fertilizerPlans.description': 'आपल्या पिकाच्या प्रकार, वाढीच्या टप्पा आणि मातीच्या परिस्थितीच्या आधारे वैयक्तिकृत खत वेळापत्रक मिळवा.',
    'feature.weather.title': 'हवामान मार्गदर्शन',
    'feature.weather.description': 'अनिष्ट हवामानाच्या परिस्थितीपासून आपल्या पिकांचे संरक्षण करण्यासाठी रिअल-टाइम हवामान अलर्ट आणि शेती सल्ला मिळवा.',
    'feature.marketPrices.title': 'बाजार भाव',
    'feature.marketPrices.description': 'कमोडिटीच्या किमतींचा मागोवा घ्या आणि आपल्या उत्पादनाची विक्री करण्यासाठी सर्वोत्तम वेळ जाणून घ्या.',
    'feature.projects.title': 'पिक प्रकल्प',
    'feature.projects.description': 'बीजापासून कापणीपर्यंत आपल्या शेतीच्या प्रकल्पांचे व्यवस्थापन करा.',
    
    // Common
    'common.open': 'खोलें',
    'common.voice': 'आवाज',
    'common.download': 'डाउनलोड',
    'common.save': 'जतन करा',
    'common.cancel': 'रद्द करा',
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी',
    'common.success': 'यश',
    
    // Stats
    'stats.farmersHelped': 'किसानांना मदत केली',
    'stats.accuracyRate': 'सुसंगतता दर',
    'stats.supportAvailable': 'सहाय्य उपलब्ध',
    
    // Soil Analysis Page
    'soil.title': 'माती विश्लेषण आणि शिफारसी',
    'soil.subtitle': 'AI-संचालित विश्लेषण आणि शिफारसींसाठी आपल्या मातीच्या रिपोर्टला अपलोड करा',
    'soil.upload': 'माती रिपोर्ट अपलोड करा',
    'soil.analyze': 'AI सह विश्लेषण करा',
    'soil.recommendations': 'AI शिफारसी',
    'soil.generateReport': 'रिपोर्ट तयार करा',
    'soil.noFile': 'कृपया प्रथम मातीचा रिपोर्ट अपलोड करा',
    'soil.analyzing': 'आपल्या मातीच्या रिपोर्टचे विश्लेषण केले जात आहे...',
    
    // Disease Detection Page
    'disease.title': 'पिक रोग ओळख',
    'disease.subtitle': 'तत्काळ AI निदानासाठी रोगग्रस्त पिकांचे चित्र अपलोड करा',
    'disease.upload': 'पिकाचे चित्र अपलोड करा',
    'disease.detect': 'రोग ओळखा',
    'disease.diagnosis': 'రोग నిర్ధారణ',
    'disease.treatment': 'చికిత్స శిఫారసులు',
    'disease.noImage': 'కృపయా ముందు ఒక పిక్చర్ అప్లోడ్ చేయండి',
    'disease.detecting': 'పిక్చర్ విశ్లేషణ జరుగుతోంది...',
    
    // Fertilizer Plans Page
    'fertilizer.title': 'खत शिफारसी',
    'fertilizer.subtitle': 'आपल्या पिकांसाठी वैयक्तिकृत खत योजना मिळवा',
    'fertilizer.selectCrop': 'पिकाचा प्रकार निवडा',
    'fertilizer.selectStage': 'वाढीचा टप्पा निवडा',
    'fertilizer.getPlan': 'खत योजना मिळवा',
    'fertilizer.recommendations': 'खत शिफारसी',
    'fertilizer.schedule': 'अर्ज वेळापत्रक',
    'fertilizer.selectBoth': 'कृपया पिकाचा प्रकार आणि वाढीचा टप्पा दोन्ही निवडा',
    
    // Weather Page
    'weather.title': 'हवामान आणि शेती मार्गदर्शन',
    'weather.subtitle': 'रिअल-टाइम हवामान अद्यतने आणि शेती सल्ला',
    'weather.current': 'सध्याचे हवामान',
    'weather.forecast': 'हवामानाचा अंदाज',
    'weather.advice': 'शेती सल्ला',
    'weather.alerts': 'हवामान अलर्ट',
    
    // Market Prices Page
    'market.title': 'बाजार भाव आणि विक्री मार्गदर्शक',
    'market.subtitle': 'कमोडिटीच्या किमतींचा मागोवा घ्या आणि विक्रीसाठी शिफारसी मिळवा',
    'market.prices': 'सध्याचे बाजार भाव',
    'market.trends': 'किमतींची प्रवृत्ती',
    'market.recommendations': 'विक्री शिफारसी',
    'market.selectCrop': 'पिक निवडा',
    
    // Projects Page
    'projects.title': 'पिक प्रकल्प व्यवस्थापन',
    'projects.subtitle': 'बीजापासून कापणीपर्यंत आपल्या शेतीच्या प्रकल्पांचे व्यवस्थापन करा',
    'projects.create': 'नवीन प्रकल्प तयार करा',
    'projects.active': 'सक्रिय प्रकल्प',
    'projects.completed': 'पूर्ण झालेले प्रकल्प',
    'projects.view': 'प्रकल्प पहा',
    'projects.edit': 'प्रकल्प संपादित करा',
    
    // Auth Pages
    'auth.login': 'आपल्या खात्यात लॉगिन करा',
    'auth.signup': 'नवीन खाते तयार करा',
    'auth.email': 'ईमेल पत्ता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्डची पुष्टी करा',
    'auth.name': 'पूर्ण नाव',
    'auth.phone': 'फोन नंबर',
    'auth.loginButton': 'लॉगिन',
    'auth.signupButton': 'साइन अप',
    'auth.switchToSignup': 'खाते नाही का? साइन अप करा',
    'auth.switchToLogin': 'Already have an account? Login',
    'auth.forgotPassword': 'पासवर्ड विसरलात का?',
    'auth.mobile': 'मोबाइल नंबर',
    'auth.location': 'स्थान',
    'auth.age': 'वय',
    'auth.enterName': 'आपले पूर्ण नाव प्रविष्ट करा',
    'auth.enterMobile': 'आपला मोबाइल नंबर प्रविष्ट करा',
    'auth.enterPassword': 'आपला पासवर्ड प्रविष्ट करा',
    'auth.confirmPasswordText': 'आपल्या पासवर्डची पुष्टी करा',
    'auth.selectLocation': 'आपले स्थान निवडा',
    'auth.enterAge': 'आपले वय प्रविष्ट करा',
    'auth.selectFarmerType': 'किसान प्रकार निवडा',
    'auth.namePlaceholder': 'आपले पूर्ण नाव प्रविष्ट करा',
    'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
    'auth.passwordPlaceholder': 'एक मजबूत पासवर्ड प्रविष्ट करा',
    'auth.confirmPasswordPlaceholder': 'आपला पासवर्ड पुन्हा प्रविष्ट करा',
    'auth.agePlaceholder': 'आपले वय प्रविष्ट करा',
    'auth.selectLocationPlaceholder': 'आपला राज्य निवडा',
    'auth.passwordMismatch': 'पासवर्ड जुळत नाहीत!',
    'auth.dontHaveAccount': 'खाते नाही का?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.farmerType.label': 'किसान प्रकार',
    'auth.farmerType.placeholder': 'కిసాన్ రకం ఎంచుకోండి',
    'auth.farmerType.small': 'చిన్న రైతు',
    'auth.farmerType.marginal': 'సరిహద్దు రైతు',
    'auth.farmerType.business': 'వ్యాపార రైతు',
  },
  
  ta: {
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.soilAnalysis': 'மண் பகுப்பாய்வு',
    'nav.diseaseDetection': 'நோய் கண்டறிதல்',
    'nav.fertilizerPlans': 'உர திட்டங்கள்',
    'nav.weather': 'வானிலை',
    'nav.marketPrices': 'சந்தை விலை',
    'nav.projects': 'திட்டங்கள்',
    'nav.voice': 'குரல்',
    'nav.login': 'உள்நுழைவு',
    
    // Home page
    'home.title': 'ஸ்மார்ட் விவசாயம்',
    'home.titleAccent': 'AI தொழில்நுட்பம்',
    'home.subtitle': 'AI இயக்கப்படும் மண் பகுப்பாய்வு, நோய் கண்டறிதல் மற்றும் பயிர் மேலாண்மை மூலம் உங்கள் விவசாயத்தில் புரட்சி ஏற்படுத்துங்கள். உங்கள் உள்ளூர் மொழியில் குரல் உதவியுடன் நிபுணர் ஆலோசனை பெறுங்கள்.',
    'home.startButton': 'ஸ்மார்ட் விவசாயம் தொடங்குங்கள்',
    'home.demoButton': 'டெமோ பார்க்க',
    'home.featuresTitle': 'முழுமையான விவசாய தீர்வு',
    'home.featuresSubtitle': 'மண் பரிசோதனை முதல் பயிர் மேலாண்மை வரை, எங்கள் AI இயக்கப்படும் தளத்தில் பல மொழிகளில் நவீன விவசாயிகளுக்கு விரிவான ஆதரவு வழங்கப்படுகிறது.',
    'home.ctaTitle': 'உங்கள் விவசாயத்தை மாற்ற தயாரா?',
    'home.ctaSubtitle': 'ஆயிரக்கணக்கான விவசாயிகள் ஏற்கனவே AI பயன்படுத்தி தங்கள் பயிர் விளைவு மற்றும் லாபத்தை அதிகரிக்கின்றனர்.',
    'home.trialButton': 'இலவச முயற்சி தொடங்குங்கள்',
    'home.supportButton': 'ஆதரவை தொடர்பு கொள்ளுங்கள்',
    'home.demo':'ஸ்மார்ட் க்ராப் அட்வைசரி என்பது விவசாயிகள் விளைச்சலை அதிகரிக்க, அபாயங்களை குறைக்க மற்றும் சிறந்த முடிவுகளை எடுக்க உதவும் செயற்கை நுண்ணறிவு (AI) அடிப்படையிலான தளம். இது பட அடிப்படையிலான நோய் கண்டறிதல், மண் அறிக்கைகள் மூலம் சரியான பயிர் மற்றும் உர பரிந்துரைகள் மற்றும் ஒவ்வொரு பிராந்தியத்திற்கும் தனிப்பட்ட பயிர் பரிந்துரைகள் வழங்குகிறது. விவசாயிகள் தங்கள் வயல்களை பாதுகாக்கவும், பாசனத்தை திட்டமிடவும் நேரம் தவறாமல் வானிலை எச்சரிக்கைகளைப் பெறுகிறார்கள். இந்த அமைப்பு ஒவ்வொரு பயிருக்கும் திட்டங்களை உருவாக்கி பராமரிப்பதற்கும், சந்தை விலைகளை நேரடியாக அறியவும், உர திட்டத்தை பின்பற்றவும் உதவுகிறது. இத்தகைய அம்சங்கள் விவசாயிகளை உற்பத்தி அதிகரிக்க, செலவுகளை குறைக்க மற்றும் சிறந்த விலையைப் பெற வலுவூட்டுகின்றன.',
    'home.demobutton':'டெமோ கேளுங்கள்',
    'home.stopDemoVoiceButton': 'டெமோ நிறுத்து',
    // Features
    'feature.soilAnalysis.title': 'மண் பகுப்பாய்வு',
    'feature.soilAnalysis.description': 'மண் அறிக்கைகளை பதிவேற்றவும், பயிர்களின் சிறந்த வளர்ச்சி மற்றும் மண் ஆரோக்கியத்தை மேம்படுத்த AI-அடிப்படையிலான பரிந்துரைகளைப் பெறவும்.',
    'feature.diseaseDetection.title': 'நோய் கண்டறிதல்',
    'feature.diseaseDetection.description': 'நோயால் பாதிக்கப்பட்ட பயிர்களின் புகைப்படங்களை எடுத்து, எங்கள் AI-இல் இருந்து உடனடி நோயியல் மற்றும் சிகிச்சை பரிந்துரைகளைப் பெறவும்.',
    'feature.fertilizerPlans.title': 'உர திட்டங்கள்',
    'feature.fertilizerPlans.description': 'உங்கள் பயிர் வகை, வளர்ச்சி நிலை மற்றும் மண் நிலைமைகளை அடிப்படையாகக் கொண்டு தனிப்பயனாக்கப்பட்ட உர அட்டவணைகளைப் பெறவும்.',
    'feature.weather.title': 'வானிலை வழிகாட்டுதல்',
    'feature.weather.description': 'எதிர்மறை வானிலை நிலைமைகளிலிருந்து உங்கள் பயிர்களைப் பாதுகாக்க நேரடி வானிலை எச்சரிக்கைகள் மற்றும் விவசாய ஆலோசனைகள்.',
    'feature.marketPrices.title': 'சந்தை விலை',
    'feature.marketPrices.description': 'பொருளாதார விலைகளை கண்காணிக்கவும், உங்கள் உற்பத்தியை விற்க சிறந்த நேரம் பற்றி அறிவார்ந்த உள்ளுணர்வுகளைப் பெறவும்.',
    'feature.projects.title': 'பயிர் திட்டங்கள்',
    'feature.projects.description': 'விதை முதல் அறுவடை வரை உங்கள் விவசாய திட்டங்களை நிர்வகிக்கவும்.',

    // Common
    'common.open': 'திற',
    'common.voice': 'குரல்',
    'common.download': 'பதிவிறக்கம்',
    'common.save': 'சேமிக்கவும்',
    'common.cancel': 'ரத்து செய்',
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    
    // Stats
    'stats.farmersHelped': 'உதவிய விவசாயிகள்',
    'stats.accuracyRate': 'துல்லியத்திற்கான விகிதம்',
    'stats.supportAvailable': 'உதவி கிடைக்கிறது',
    
    // Soil Analysis Page
    'soil.title': 'மண் பகுப்பாய்வு & பரிந்துரைகள்',
    'soil.subtitle': 'AI-அடிப்படையிலான பகுப்பாய்வு மற்றும் பரிந்துரைகளுக்கு உங்கள் மண் அறிக்கையை பதிவேற்றவும்',
    'soil.upload': 'மண் அறிக்கையை பதிவேற்றவும்',
    'soil.analyze': 'AI உடன் பகுப்பாய்வு செய்',
    'soil.recommendations': 'AI பரிந்துரைகள்',
    'soil.generateReport': 'அறிக்கையை உருவாக்கவும்',
    'soil.noFile': 'முதலில் ஒரு மண் அறிக்கையைப் பதிவேற்றவும்',
    'soil.analyzing': 'உங்கள் மண் அறிக்கையைப் பகுப்பாய்வு செய்கிறோம்...',
    
    // Disease Detection Page
    'disease.title': 'பயிர் நோய் கண்டறிதல்',
    'disease.subtitle': 'உடனடி AI நோயியல் கண்டு பிடிக்க நோய் பாதித்த பயிர்களின் படங்களை பதிவேற்றவும்',
    'disease.upload': 'பயிர் படத்தை பதிவேற்றவும்',
    'disease.detect': 'நோயை கண்டறி',
    'disease.diagnosis': 'நோயியல்',
    'disease.treatment': 'சிகிச்சை பரிந்துரைகள்',
    'disease.noImage': 'முதலில் ஒரு பயிர் படத்தை பதிவேற்றவும்',
    'disease.detecting': 'பயிர் படத்தைப் பகுப்பாய்வு செய்கிறோம்...',
    
    // Fertilizer Plans Page
    'fertilizer.title': 'உர பரிந்துரைகள்',
    'fertilizer.subtitle': 'உங்கள் பயிர்களுக்கு தனிப்பயனாக்கப்பட்ட உர திட்டங்களைப் பெறுங்கள்',
    'fertilizer.selectCrop': 'பயிர் வகையைத் தேர்ந்தெடுக்கவும்',
    'fertilizer.selectStage': 'வளர்ச்சி நிலையைத் தேர்ந்தெடுக்கவும்',
    'fertilizer.getPlan': 'உர திட்டத்தைப் பெறுங்கள்',
    'fertilizer.recommendations': 'உர பரிந்துரைகள்',
    'fertilizer.schedule': 'சேமிப்பு அட்டவணை',
    'fertilizer.selectBoth': 'தயவுசெய்து பயிர் வகை மற்றும் வளர்ச்சி நிலை இரண்டையும் தேர்ந்தெடுக்கவும்',
    
    // Weather Page
    'weather.title': 'வானிலை & விவசாய வழிகாட்டுதல்',
    'weather.subtitle': 'நேரடி வானிலை புதுப்பிப்புகள் மற்றும் விவசாய ஆலோசனைகள்',
    'weather.current': 'தற்போதைய வானிலை',
    'weather.forecast': 'வானிலை முன்னறிவிப்பு',
    'weather.advice': 'விவசாய ஆலோசனை',
    'weather.alerts': 'வானிலை எச்சரிக்கைகள்',
    
    // Market Prices Page
    'market.title': 'சந்தை விலை & விற்பனை வழிகாட்டி',
    'market.subtitle': 'பொருளாதார விலைகளை கண்காணிக்கவும் மற்றும் விற்பனைக்கு பரிந்துரைகளைப் பெறவும்',
    'market.prices': 'தற்போதைய சந்தை விலைகள்',
    'market.trends': 'விலை போக்குகள்',
    'market.recommendations': 'விற்பனை பரிந்துரைகள்',
    'market.selectCrop': 'பயிர் தேர்ந்தெடுக்கவும்',
    
    // Projects Page
    'projects.title': 'பயிர் திட்ட மேலாண்மை',
    'projects.subtitle': 'விதை முதல் காய்கறி வரை உங்கள் விவசாய திட்டங்களை நிர்வகிக்கவும்',
    'projects.create': 'புதிய திட்டம் உருவாக்கவும்',
    'projects.active': 'செயலில் உள்ள திட்டங்கள்',
    'projects.completed': 'முடிக்கப்பட்ட திட்டங்கள்',
    'projects.view': 'திட்டத்தைப் பார்வையிடவும்',
    'projects.edit': 'திட்டத்தைத் திருத்தவும்',
    
    // Auth Pages
    'auth.login': 'உங்கள் கணக்கில் உள்நுழைக',
    'auth.signup': 'புதிய கணக்கை உருவாக்கவும்',
    'auth.email': 'மின்னஞ்சல் முகவரி',
    'auth.password': 'கடவுச்சொல்',
    'auth.confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'auth.name': 'முழு பெயர்',
    'auth.phone': 'தொலைபேசி எண்',
    'auth.loginButton': 'உள்நுழைவு',
    'auth.signupButton': 'பதிவு செய்யவும்',
    'auth.switchToSignup': 'கணக்கு இல்லையா? பதிவு செய்யவும்',
    'auth.switchToLogin': 'Already have an account? Login',
    'auth.forgotPassword': 'கடவுச்சொல் மறந்துவிட்டீர்களா?',
    'auth.mobile': 'மொபைல் எண்',
    'auth.location': 'இடம்',
    'auth.age': 'வயது',
    'auth.enterName': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'auth.enterMobile': 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
    'auth.enterPassword': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'auth.confirmPasswordText': 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'auth.selectLocation': 'உங்கள் இடத்தைத் தேர்ந்தெடுக்கவும்',
    'auth.enterAge': 'உங்கள் வயதை உள்ளிடவும்',
    'auth.selectFarmerType': 'விவசாயி வகையைத் தேர்ந்தெடுக்கவும்',
    'auth.namePlaceholder': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
    'auth.passwordPlaceholder': 'ஒரு வலுவான கடவுச்சொல்லை உள்ளிடவும்',
    'auth.confirmPasswordPlaceholder': 'உங்கள் கடவுச்சொல்லை மீண்டும் உள்ளிடவும்',
    'auth.agePlaceholder': 'உங்கள் வயதை உள்ளிடவும்',
    'auth.selectLocationPlaceholder': 'உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    'auth.passwordMismatch': 'கடவுச்சொற்கள் பொருந்தவில்லை!',
    'auth.dontHaveAccount': 'கணக்கு இல்லையா?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.farmerType.label': 'விவசாயி வகை',
    'auth.farmerType.placeholder': 'விவசாயி வகையைத் தேர்ந்தெடுக்கவும்',
    'auth.farmerType.small': 'சிறு விவசாயி',
    'auth.farmerType.marginal': 'சரிவரிசை விவசாயி',
    'auth.farmerType.business': 'வணிக விவசாயி',
  },
  gu: {
  // Navigation
  'nav.home': 'હોમ',
  'nav.soilAnalysis': 'માટી વિશ્લેષણ',
  'nav.diseaseDetection': 'રોગ ઓળખ',
  'nav.fertilizerPlans': 'ખાત યોજના',
  'nav.weather': 'હવામાન',
  'nav.marketPrices': 'બજાર ભાવ',
  'nav.projects': 'પ્રોજેક્ટ્સ',
  'nav.voice': 'અવાજ',
  'nav.login': 'લોગિન',

  // Home page
  'home.title': 'સ્માર્ટ ખેતી સાથે',
  'home.titleAccent': 'AI ટેક્નોલોજી',
  'home.subtitle': 'AI આધારિત માટી વિશ્લેષણ, રોગ ઓળખ અને પાક વ્યવસ્થાપનથી તમારી ખેતીમાં ક્રાંતિ લાવો. તમારી સ્થાનિક ભાષામાં અવાજ સહાયથી નિષ્ણાત સલાહ મેળવો.',
  'home.startButton': 'સ્માર્ટ ખેતી શરૂ કરો',
  'home.demoButton': 'ડેમો જુઓ',
  'home.featuresTitle': 'સંપૂર્ણ ખેતી સોલ્યુશન',
  'home.featuresSubtitle': 'માટી પરીક્ષણથી પાક વ્યવસ્થાપન સુધી, અમારો AI આધારિત પ્લેટફોર્મ અનેક ભાષાઓમાં આધુનિક ખેડુતો માટે વ્યાપક સહાય આપે છે.',
  'home.ctaTitle': 'તમારી ખેતી બદલવા તૈયાર છો?',
  'home.ctaSubtitle': 'હજારો ખેડુતો સાથે જોડાઓ, જે પહેલેથી જ AI નો ઉપયોગ કરીને પાકની ઉપજ અને નફો વધારી રહ્યા છે.',
  'home.trialButton': 'મફત ટ્રાયલ શરૂ કરો',
  'home.supportButton': 'સપોર્ટ સંપર્ક કરો',
  'home.demo':'સ્માર્ટ ક્રોપ એડવાઈઝરી એ એઆઈ આધારિત પ્લેટફોર્મ છે જે ખેડૂતોને ઉત્પાદન વધારવામાં, જોખમ ઘટાડવામાં અને યોગ્ય નિર્ણયો લેવામાં મદદ કરે છે. તે ઈમેજ આધારિત રોગ શોધ, માટી રિપોર્ટ વિશ્લેષણ દ્વારા યોગ્ય પાક અને ખાતરની ભલામણો અને દરેક વિસ્તાર માટે વ્યક્તિગત પાક સૂચનો આપે છે. ખેડૂતોને સમયસર હવામાન ચેતવણીઓ મળે છે જેથી તેઓ પાકને સુરક્ષિત રાખી શકે અને સિંચાઈની યોજના બનાવી શકે. આ સિસ્ટમ ખેડૂતોને દરેક પાક માટે પ્રોજેક્ટ બનાવવાની અને જાળવી રાખવાની, વાસ્તવિક-સમયના બજાર ભાવ જાણવા અને ખાતર યોજના અનુસરવાની સુવિધા આપે છે. આ બધી સુવિધાઓ ખેડૂતોને ઉત્પાદનક્ષમતા વધારવામાં, ખર્ચ ઘટાડવામાં અને વધુ સારા ભાવ મેળવવામાં સક્ષમ બનાવે છે.',
  'home.demobutton':'ડેમો સાંભળો',
   'home.stopDemoVoiceButton':  'ડેમો બંધ કરો',
 

  // Features
  'feature.soilAnalysis.title': 'માટી વિશ્લેષણ',
  'feature.soilAnalysis.description': 'માટી રિપોર્ટ અપલોડ કરો અને શ્રેષ્ઠ પાક વૃદ્ધિ અને માટી આરોગ્ય સુધારવા માટે AI આધારિત ભલામણો મેળવો.',
  'feature.diseaseDetection.title': 'રોગ ઓળખ',
  'feature.diseaseDetection.description': 'રોગગ્રસ્ત પાકના ફોટા લો અને અમારા AI પાસેથી તાત્કાલિક નિદાન અને સારવારની ભલામણો મેળવો.',
  'feature.fertilizerPlans.title': 'ખાત યોજના',
  'feature.fertilizerPlans.description': 'તમારા પાકના પ્રકાર, વૃદ્ધિ સ્ટેજ અને માટી સ્થિતિના આધારે વ્યક્તિગત ખાત શેડ્યૂલ મેળવો.',
  'feature.weather.title': 'હવામાન માર્ગદર્શન',
  'feature.weather.description': 'અનિચ્છનીય હવામાન સ્થિતિથી પાકને બચાવવા માટે રિયલ-ટાઈમ હવામાન એલર્ટ અને ખેતી સલાહ.',
  'feature.marketPrices.title': 'બજાર ભાવ',
  'feature.marketPrices.description': 'વસ્તુના ભાવ ટ્રેક કરો અને વેચાણ માટે શ્રેષ્ઠ સમય વિશે બુદ્ધિશાળી જાણકારી મેળવો.',
  'feature.projects.title': 'પાક પ્રોજેક્ટ્સ',
  'feature.projects.description': 'વિસ્તૃત ટ્રેકિંગ અને રિપોર્ટિંગ સાથે બીજથી પાક સુધી તમારી ખેતી પ્રોજેક્ટ્સનું સંચાલન કરો.',

  // Common
  'common.open': 'ખોલો',
  'common.voice': 'અવાજ',
  'common.download': 'ડાઉનલોડ',
  'common.save': 'સાચવો',
  'common.cancel': 'રદ કરો',
  'common.loading': 'લોડ થઈ રહ્યું છે...',
  'common.error': 'ભૂલ',
  'common.success': 'સફળતા',

  // Stats
  'stats.farmersHelped': 'ખેડુતોને મદદ',
  'stats.accuracyRate': 'શુદ્ધતા દર',
  'stats.supportAvailable': 'સહાય ઉપલબ્ધ',

  // Soil Analysis Page
  'soil.title': 'માટી વિશ્લેષણ અને ભલામણો',
  'soil.subtitle': 'AI આધારિત વિશ્લેષણ અને ભલામણ માટે તમારી માટી રિપોર્ટ અપલોડ કરો',
  'soil.upload': 'માટી રિપોર્ટ અપલોડ કરો',
  'soil.analyze': 'AI સાથે વિશ્લેષણ કરો',
  'soil.recommendations': 'AI ભલામણો',
  'soil.generateReport': 'રિપોર્ટ બનાવો',
  'soil.noFile': 'કૃપા કરીને પહેલા માટી રિપોર્ટ અપલોડ કરો',
  'soil.analyzing': 'તમારી માટી રિપોર્ટનું વિશ્લેષણ થઈ રહ્યું છે...',

  // Disease Detection Page
  'disease.title': 'પાક રોગ ઓળખ',
  'disease.subtitle': 'તાત્કાલિક AI નિદાન માટે રોગગ્રસ્ત પાકના ફોટા અપલોડ કરો',
  'disease.upload': 'પાકનો ફોટો અપલોડ કરો',
  'disease.detect': 'રોગ ઓળખો',
  'disease.diagnosis': 'રોગ નિદાન',
  'disease.treatment': 'ઉપચારની ભલામણો',
  'disease.noImage': 'કૃપા કરીને પહેલા પાકનો ફોટો અપલોડ કરો',
  'disease.detecting': 'પાકના ફોટાનું વિશ્લેષણ થઈ રહ્યું છે...',

  // Fertilizer Plans Page
  'fertilizer.title': 'ખાત ભલામણો',
  'fertilizer.subtitle': 'તમારા પાક માટે વ્યક્તિગત ખાત યોજના મેળવો',
  'fertilizer.selectCrop': 'પાકનો પ્રકાર પસંદ કરો',
  'fertilizer.selectStage': 'વૃદ્ધિ સ્ટેજ પસંદ કરો',
  'fertilizer.getPlan': 'ખાત યોજના મેળવો',
  'fertilizer.recommendations': 'ખાત ભલામણો',
  'fertilizer.schedule': 'અરજી શેડ્યૂલ',
  'fertilizer.selectBoth': 'કૃપા કરીને પાકનો પ્રકાર અને વૃદ્ધિ સ્ટેજ બંને પસંદ કરો',

  // Weather Page
  'weather.title': 'હવામાન અને ખેતી માર્ગદર્શન',
  'weather.subtitle': 'રિયલ-ટાઈમ હવામાન અપડેટ અને ખેતી સલાહ',
  'weather.current': 'વર્તમાન હવામાન',
  'weather.forecast': 'હવામાન અનુમાન',
  'weather.advice': 'ખેતી સલાહ',
  'weather.alerts': 'હવામાન એલર્ટ',

  // Market Prices Page
  'market.title': 'બજાર ભાવ અને વેચાણ માર્ગદર્શિકા',
  'market.subtitle': 'વસ્તુના ભાવ ટ્રેક કરો અને વેચાણ માટે ભલામણો મેળવો',
  'market.prices': 'વર્તમાન બજાર ભાવ',
  'market.trends': 'ભાવની પ્રવૃત્તિ',
  'market.recommendations': 'વેચાણ ભલામણો',
  'market.selectCrop': 'પાક પસંદ કરો',

  // Projects Page
  'projects.title': 'પાક પ્રોજેક્ટ સંચાલન',
  'projects.subtitle': 'બીજથી પાક સુધી તમારી ખેતી પ્રોજેક્ટ્સનું સંચાલન કરો',
  'projects.create': 'નવું પ્રોજેક્ટ બનાવો',
  'projects.active': 'સક્રિય પ્રોજેક્ટ્સ',
  'projects.completed': 'પૂર્ણ થયેલ પ્રોજેક્ટ્સ',
  'projects.view': 'પ્રોજેક્ટ જુઓ',
  'projects.edit': 'પ્રોજેક્ટ સંપાદિત કરો',

  // Auth Pages
  'auth.login': 'તમારા ખાતામાં લોગિન કરો',
  'auth.signup': 'નવું ખાતું બનાવો',
  'auth.email': 'ઈમેલ એડ્રેસ',
  'auth.password': 'પાસવર્ડ',
  'auth.confirmPassword': 'પાસવર્ડની પુષ્ટિ કરો',
  'auth.name': 'પૂર્ણ નામ',
  'auth.phone': 'ફોન નંબર',
  'auth.loginButton': 'લોગિન',
  'auth.signupButton': 'સાઇન અપ',
  'auth.switchToSignup': 'ખાતું નથી? સાઇન અપ કરો',
  'auth.switchToLogin': 'પહેલેથી જ ખાતું છે? લોગિન કરો',
  'auth.forgotPassword': 'પાસવર્ડ ભૂલી ગયા?',
  'auth.mobile': 'મોબાઇલ નંબર',
  'auth.location': 'સ્થાન',
  'auth.age': 'ઉંમર',
  'auth.enterName': 'તમારું પૂર્ણ નામ દાખલ કરો',
  'auth.enterMobile': 'તમારો મોબાઇલ નંબર દાખલ કરો',
  'auth.enterPassword': 'તમારો પાસવર્ડ દાખલ કરો',
  'auth.confirmPasswordText': 'તમારા પાસવર્ડની પુષ્ટિ કરો',
  'auth.selectLocation': 'તમારું સ્થાન પસંદ કરો',
  'auth.enterAge': 'તમારી ઉંમર દાખલ કરો',
  'auth.selectFarmerType': 'ખેડૂત પ્રકાર પસંદ કરો',
  'auth.namePlaceholder': 'તમારું પૂર્ણ નામ દાખલ કરો',
  'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
  'auth.passwordPlaceholder': 'મજબૂત પાસવર્ડ દાખલ કરો',
  'auth.confirmPasswordPlaceholder': 'પાસવર્ડ ફરીથી દાખલ કરો',
  'auth.agePlaceholder': 'તમારી ઉંમર દાખલ કરો',
  'auth.selectLocationPlaceholder': 'તમારું રાજ્ય પસંદ કરો',
  'auth.passwordMismatch': 'પાસવર્ડ મેળ ખાતા નથી!',
  'auth.dontHaveAccount': 'ખાતું નથી?',
  'auth.alreadyHaveAccount': 'પહેલેથી જ ખાતું છે?',
  'auth.farmerType.label': 'ખેડૂત પ્રકાર',
  'auth.farmerType.placeholder': 'ખેડૂત પ્રકાર પસંદ કરો',
  'auth.farmerType.small': 'નાનો ખેડૂત',
  'auth.farmerType.marginal': 'સીમાંત ખેડૂત',
  'auth.farmerType.business': 'વ્યવસાયિક ખેડૂત',
},
kn: {
  // Navigation
  'nav.home': 'ಮುಖಪುಟ',
  'nav.soilAnalysis': 'ಮಣ್ಣು ವಿಶ್ಲೇಷಣೆ',
  'nav.diseaseDetection': 'ರೋಗ ಪತ್ತೆ',
  'nav.fertilizerPlans': 'ಸಾರ ಯೋಜನೆ',
  'nav.weather': 'ಹವಾಮಾನ',
  'nav.marketPrices': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
  'nav.projects': 'ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು',
  'nav.voice': 'ಧ್ವನಿ',
  'nav.login': 'ಲಾಗಿನ್',

  // Home page
  'home.title': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ',
  'home.titleAccent': 'AI ತಂತ್ರಜ್ಞಾನ',
  'home.subtitle': 'AI ಆಧಾರಿತ ಮಣ್ಣು ವಿಶ್ಲೇಷಣೆ, ರೋಗ ಪತ್ತೆ ಮತ್ತು ಬೆಳೆ ನಿರ್ವಹಣೆಯೊಂದಿಗೆ ನಿಮ್ಮ ಕೃಷಿಯಲ್ಲಿ ಕ್ರಾಂತಿ ತರಿರಿ. ನಿಮ್ಮ ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ಧ್ವನಿ ಸಹಾಯದಿಂದ ತಜ್ಞ ಸಲಹೆ ಪಡೆಯಿರಿ.',
  'home.startButton': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಆರಂಭಿಸಿ',
  'home.demoButton': 'ಡೆಮೊ ನೋಡಿ',
  'home.featuresTitle': 'ಪೂರ್ಣ ಕೃಷಿ ಪರಿಹಾರ',
  'home.featuresSubtitle': 'ಮಣ್ಣು ಪರೀಕ್ಷೆಯಿಂದ ಬೆಳೆ ನಿರ್ವಹಣೆವರೆಗೆ, ನಮ್ಮ AI ಆಧಾರಿತ ವೇದಿಕೆ ಅನೇಕ ಭಾಷೆಗಳಲ್ಲಿ ಆಧುನಿಕ ರೈತರಿಗೆ ಸಮಗ್ರ ಬೆಂಬಲ ಒದಗಿಸುತ್ತದೆ.',
  'home.ctaTitle': 'ನಿಮ್ಮ ಕೃಷಿಯನ್ನು ಬದಲಾಯಿಸಲು ಸಿದ್ಧ?',
  'home.ctaSubtitle': 'ಸಾವಿರಾರು ರೈತರು ಈಗಾಗಲೇ AI ಬಳಸಿ ತಮ್ಮ ಬೆಳೆ ಉತ್ಪಾದನೆ ಮತ್ತು ಲಾಭವನ್ನು ಹೆಚ್ಚಿಸುತ್ತಿದ್ದಾರೆ.',
  'home.trialButton': 'ಉಚಿತ ಪ್ರಯೋಗ ಆರಂಭಿಸಿ',
  'home.supportButton': 'ಬೆಂಬಲ ಸಂಪರ್ಕಿಸಿ',
  'home.demo':'ಸ್ಮಾರ್ಟ್ ಕ್ರಾಪ್ ಸಲಹೆಗಾರಿಕೆ ಒಂದು AI ಆಧಾರಿತ ವೇದಿಕೆಯಾಗಿದೆ, ಇದು ರೈತರಿಗೆ ಉತ್ಪಾದನೆ ಹೆಚ್ಚಿಸಲು, ಅಪಾಯಗಳನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಮತ್ತು ಉತ್ತಮ ನಿರ್ಧಾರಗಳನ್ನು ಕೈಗೊಳ್ಳಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಇದು ಚಿತ್ರ ಆಧಾರಿತ ರೋಗ ಪತ್ತೆ, ಮಣ್ಣಿನ ವರದಿ ವಿಶ್ಲೇಷಣೆ ಮೂಲಕ ಸರಿಯಾದ ಬೆಳೆ ಮತ್ತು ರಸಗೊಬ್ಬರ ಶಿಫಾರಸುಗಳು, ಮತ್ತು ಪ್ರತಿ ಪ್ರದೇಶಕ್ಕೆ ಹೊಂದುವ ಬೆಳೆ ಶಿಫಾರಸುಗಳನ್ನು ನೀಡುತ್ತದೆ. ರೈತರಿಗೆ ಸಮಯಕ್ಕೆ ಸರಿಯಾದ ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು ಸಿಗುತ್ತವೆ, ಇದರಿಂದ ಹೊಲಗಳನ್ನು ರಕ್ಷಿಸಬಹುದು ಮತ್ತು ನೀರಾವರಿ ಯೋಜನೆ ಮಾಡಬಹುದು. ಈ ವ್ಯವಸ್ಥೆ ರೈತರಿಗೆ ಪ್ರತಿಯೊಂದು ಬೆಳೆಗೂ ಪ್ರಾಜೆಕ್ಟ್ ರಚಿಸಲು ಮತ್ತು ನಿರ್ವಹಿಸಲು, ನೇರ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ರಸಗೊಬ್ಬರ ಯೋಜನೆಯನ್ನು ಅನುಸರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಒಟ್ಟಿನಲ್ಲಿ, ಈ ಸೌಲಭ್ಯಗಳು ರೈತರ ಉತ್ಪಾದಕತೆ ಹೆಚ್ಚಿಸಲು, ವೆಚ್ಚವನ್ನು ಉಳಿಸಲು ಮತ್ತು ಉತ್ತಮ ಬೆಲೆ ಪಡೆಯಲು ಸಹಕಾರಿಯಾಗುತ್ತವೆ.',
  'home.demobutton':'ಡೆಮೊ ಕೇಳಿ',
   'home.stopDemoVoiceButton': 'ಡೆಮೊ ನಿಲ್ಲಿಸಿ',
  

  // Features
  'feature.soilAnalysis.title': 'ಮಣ್ಣು ವಿಶ್ಲೇಷಣೆ',
  'feature.soilAnalysis.description': 'ಮಣ್ಣು ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಉತ್ತಮ ಬೆಳೆ ಬೆಳವಣಿಗೆ ಮತ್ತು ಮಣ್ಣು ಆರೋಗ್ಯಕ್ಕಾಗಿ AI ಆಧಾರಿತ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
  'feature.diseaseDetection.title': 'ರೋಗ ಪತ್ತೆ',
  'feature.diseaseDetection.description': 'ರೋಗಗ್ರಸ್ತ ಬೆಳೆಗಳ ಚಿತ್ರಗಳನ್ನು ತೆಗೆದು, ನಮ್ಮ AI ಮೂಲಕ ತಕ್ಷಣದ ರೋಗ ಪತ್ತೆ ಮತ್ತು ಚಿಕಿತ್ಸೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
  'feature.fertilizerPlans.title': 'ಸಾರ ಯೋಜನೆ',
  'feature.fertilizerPlans.description': 'ನಿಮ್ಮ ಬೆಳೆ ಪ್ರಕಾರ, ಬೆಳವಣಿಗೆ ಹಂತ ಮತ್ತು ಮಣ್ಣು ಸ್ಥಿತಿಯ ಆಧಾರದ ಮೇಲೆ ವೈಯಕ್ತಿಕ ಸಾರ ವೇಳಾಪಟ್ಟಿಯನ್ನು ಪಡೆಯಿರಿ.',
  'feature.weather.title': 'ಹವಾಮಾನ ಮಾರ್ಗದರ್ಶನ',
  'feature.weather.description': 'ಅನನುಕೂಲಕರ ಹವಾಮಾನದಿಂದ ಬೆಳೆಗಳನ್ನು ರಕ್ಷಿಸಲು ರಿಯಲ್-ಟೈಮ್ ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ ಮತ್ತು ಕೃಷಿ ಸಲಹೆ.',
  'feature.marketPrices.title': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
  'feature.marketPrices.description': 'ವಸ್ತು ಬೆಲೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಮಾರಾಟಕ್ಕೆ ಉತ್ತಮ ಸಮಯದ ಬಗ್ಗೆ ಬುದ್ಧಿವಂತಿಕೆ ಪಡೆಯಿರಿ.',
  'feature.projects.title': 'ಬೆಳೆ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು',
  'feature.projects.description': 'ವಿಸ್ತೃತ ಟ್ರ್ಯಾಕಿಂಗ್ ಮತ್ತು ವರದಿ ಸಹಿತ ಬೀಜದಿಂದ ಬೆಳೆವರೆಗೆ ನಿಮ್ಮ ಕೃಷಿ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',

  // Common
  'common.open': 'ತೆರೆ',
  'common.voice': 'ಧ್ವನಿ',
  'common.download': 'ಡೌನ್‌ಲೋಡ್',
  'common.save': 'ಉಳಿಸಿ',
  'common.cancel': 'ರದ್ದು ಮಾಡಿ',
  'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
  'common.error': 'ದೋಷ',
  'common.success': 'ಯಶಸ್ಸು',

  // Stats
  'stats.farmersHelped': 'ರೈತರಿಗೆ ಸಹಾಯ',
  'stats.accuracyRate': 'ನಿಖರತೆ ದರ',
  'stats.supportAvailable': 'ಬೆಂಬಲ ಲಭ್ಯ',

  // Soil Analysis Page
  'soil.title': 'ಮಣ್ಣು ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಶಿಫಾರಸುಗಳು',
  'soil.subtitle': 'AI ಆಧಾರಿತ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ನಿಮ್ಮ ಮಣ್ಣು ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'soil.upload': 'ಮಣ್ಣು ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'soil.analyze': 'AI ಮೂಲಕ ವಿಶ್ಲೇಷಿಸಿ',
  'soil.recommendations': 'AI ಶಿಫಾರಸುಗಳು',
  'soil.generateReport': 'ವರದಿ ರಚಿಸಿ',
  'soil.noFile': 'ದಯವಿಟ್ಟು ಮೊದಲು ಮಣ್ಣು ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'soil.analyzing': 'ನಿಮ್ಮ ಮಣ್ಣು ವರದಿ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',

  // Disease Detection Page
  'disease.title': 'ಬೆಳೆ ರೋಗ ಪತ್ತೆ',
  'disease.subtitle': 'ತಕ್ಷಣದ AI ಪತ್ತೆಗೆ ರೋಗಗ್ರಸ್ತ ಬೆಳೆ ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'disease.upload': 'ಬೆಳೆ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'disease.detect': 'ರೋಗ ಪತ್ತೆ ಮಾಡಿ',
  'disease.diagnosis': 'ರೋಗ ಪತ್ತೆ',
  'disease.treatment': 'ಚಿಕಿತ್ಸೆ ಶಿಫಾರಸುಗಳು',
  'disease.noImage': 'ದಯವಿಟ್ಟು ಮೊದಲು ಬೆಳೆ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'disease.detecting': 'ಬೆಳೆ ಚಿತ್ರ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',

  // Fertilizer Plans Page
  'fertilizer.title': 'ಸಾರ ಶಿಫಾರಸುಗಳು',
  'fertilizer.subtitle': 'ನಿಮ್ಮ ಬೆಳೆಗಳಿಗೆ ವೈಯಕ್ತಿಕ ಸಾರ ಯೋಜನೆ ಪಡೆಯಿರಿ',
  'fertilizer.selectCrop': 'ಬೆಳೆ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ',
  'fertilizer.selectStage': 'ಬೆಳವಣಿಗೆ ಹಂತ ಆಯ್ಕೆಮಾಡಿ',
  'fertilizer.getPlan': 'ಸಾರ ಯೋಜನೆ ಪಡೆಯಿರಿ',
  'fertilizer.recommendations': 'ಸಾರ ಶಿಫಾರಸುಗಳು',
  'fertilizer.schedule': 'ಅರ್ಜಿಯ ವೇಳಾಪಟ್ಟಿ',
  'fertilizer.selectBoth': 'ದಯವಿಟ್ಟು ಬೆಳೆ ಪ್ರಕಾರ ಮತ್ತು ಬೆಳವಣಿಗೆ ಹಂತ ಎರಡನ್ನೂ ಆಯ್ಕೆಮಾಡಿ',

  // Weather Page
  'weather.title': 'ಹವಾಮಾನ ಮತ್ತು ಕೃಷಿ ಮಾರ್ಗದರ್ಶನ',
  'weather.subtitle': 'ರಿಯಲ್-ಟೈಮ್ ಹವಾಮಾನ ಅಪ್‌ಡೇಟ್ ಮತ್ತು ಕೃಷಿ ಸಲಹೆ',
  'weather.current': 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ',
  'weather.forecast': 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
  'weather.advice': 'ಕೃಷಿ ಸಲಹೆ',
  'weather.alerts': 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ',

  // Market Prices Page
  'market.title': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಮತ್ತು ಮಾರಾಟ ಮಾರ್ಗದರ್ಶನ',
  'market.subtitle': 'ವಸ್ತು ಬೆಲೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಮಾರಾಟ ಶಿಫಾರಸುಗಳು ಪಡೆಯಿರಿ',
  'market.prices': 'ಪ್ರಸ್ತುತ ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
  'market.trends': 'ಬೆಲೆಯ ಪ್ರವೃತ್ತಿ',
  'market.recommendations': 'ಮಾರಾಟ ಶಿಫಾರಸುಗಳು',
  'market.selectCrop': 'ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ',

  // Projects Page
  'projects.title': 'ಬೆಳೆ ಪ್ರಾಜೆಕ್ಟ್ ನಿರ್ವಹಣೆ',
  'projects.subtitle': 'ಬೀಜದಿಂದ ಬೆಳೆವರೆಗೆ ನಿಮ್ಮ ಕೃಷಿ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
  'projects.create': 'ಹೊಸ ಪ್ರಾಜೆಕ್ಟ್ ರಚಿಸಿ',
  'projects.active': 'ಸಕ್ರಿಯ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು',
  'projects.completed': 'ಪೂರ್ಣಗೊಂಡ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು',
  'projects.view': 'ಪ್ರಾಜೆಕ್ಟ್ ನೋಡಿ',
  'projects.edit': 'ಪ್ರಾಜೆಕ್ಟ್ ಸಂಪಾದಿಸಿ',

  // Auth Pages
  'auth.login': 'ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
  'auth.signup': 'ಹೊಸ ಖಾತೆ ರಚಿಸಿ',
  'auth.email': 'ಇಮೇಲ್ ವಿಳಾಸ',
  'auth.password': 'ಪಾಸ್ವರ್ಡ್',
  'auth.confirmPassword': 'ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
  'auth.name': 'ಪೂರ್ಣ ಹೆಸರು',
  'auth.phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
  'auth.loginButton': 'ಲಾಗಿನ್',
  'auth.signupButton': 'ಸೈನ್ ಅಪ್',
  'auth.switchToSignup': 'ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ',
  'auth.switchToLogin': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ',
  'auth.forgotPassword': 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ?',
  'auth.mobile': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
  'auth.location': 'ಸ್ಥಳ',
  'auth.age': 'ವಯಸ್ಸು',
  'auth.enterName': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
  'auth.enterMobile': 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
  'auth.enterPassword': 'ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
  'auth.confirmPasswordText': 'ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
  'auth.selectLocation': 'ನಿಮ್ಮ ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ',
  'auth.enterAge': 'ನಿಮ್ಮ ವಯಸ್ಸು ನಮೂದಿಸಿ',
  'auth.selectFarmerType': 'ರೈತ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ',
  'auth.namePlaceholder': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
  'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
  'auth.passwordPlaceholder': 'ಬಲವಾದ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
  'auth.confirmPasswordPlaceholder': 'ಪಾಸ್ವರ್ಡ್ ಮತ್ತೆ ನಮೂದಿಸಿ',
  'auth.agePlaceholder': 'ನಿಮ್ಮ ವಯಸ್ಸು ನಮೂದಿಸಿ',
  'auth.selectLocationPlaceholder': 'ನಿಮ್ಮ ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ',
  'auth.passwordMismatch': 'ಪಾಸ್ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ!',
  'auth.dontHaveAccount': 'ಖಾತೆ ಇಲ್ಲವೇ?',
  'auth.alreadyHaveAccount': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
  'auth.farmerType.label': 'ರೈತ ಪ್ರಕಾರ',
  'auth.farmerType.placeholder': 'ರೈತ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ',
  'auth.farmerType.small': 'ಚಿಕ್ಕ ರೈತ',
  'auth.farmerType.marginal': 'ಸೀಮಿತ ರೈತ',
  'auth.farmerType.business': 'ವ್ಯವಹಾರ ರೈತ',
},

ml: {
  // Navigation
  'nav.home': 'ഹോം',
  'nav.soilAnalysis': 'മണ്ണ് വിശകലനം',
  'nav.diseaseDetection': 'രോഗം കണ്ടെത്തല്‍',
  'nav.fertilizerPlans': 'വള പദ്ധതി',
  'nav.weather': 'വാതാവരണം',
  'nav.marketPrices': 'ചന്ത വില',
  'nav.projects': 'പ്രോജക്ടുകള്‍',
  'nav.voice': 'ശബ്ദം',
  'nav.login': 'ലോഗിന്‍',

  // Home page
  'home.title': 'സ്മാര്‍ട്ട് കൃഷി',
  'home.titleAccent': 'AI സാങ്കേതികവിദ്യ',
  'home.subtitle': 'AI അധിഷ്ഠിത മണ്ണ് വിശകലനം, രോഗം കണ്ടെത്തല്‍, വിള നയനം എന്നിവയിലൂടെ നിങ്ങളുടെ കൃഷിയില്‍ വിപ്ലവം സൃഷ്ടിക്കുക. നിങ്ങളുടെ പ്രാദേശിക ഭാഷയില്‍ ശബ്ദ സഹായത്തോടെ വിദഗ്ധ ഉപദേശം നേടൂ.',
  'home.startButton': 'സ്മാര്‍ട്ട് കൃഷി ആരംഭിക്കുക',
  'home.demoButton': 'ഡെമോ കാണുക',
  'home.featuresTitle': 'സമ്പൂര്‍ണ കൃഷി പരിഹാരം',
  'home.featuresSubtitle': 'മണ്ണ് പരിശോധന മുതല്‍ വിള നയനം വരെ, ഞങ്ങളുടെ AI അധിഷ്ഠിത പ്ലാറ്റ്ഫോം അനേകം ഭാഷകളില്‍ ആധുനിക കർഷകര്‍ക്ക് സമഗ്ര പിന്തുണ നല്‍കുന്നു.',
  'home.ctaTitle': 'നിങ്ങളുടെ കൃഷി മാറ്റാന്‍ തയ്യാറാണോ?',
  'home.ctaSubtitle': 'ആയിരക്കണക്കിന് കർഷകര്‍ ഇതിനകം തന്നെ AI ഉപയോഗിച്ച് വിളയുടെ ഉല്പാദനവും ലാഭവും വര്‍ദ്ധിപ്പിക്കുന്നു.',
  'home.trialButton': 'ഉചിത ട്രയല്‍ ആരംഭിക്കുക',
  'home.supportButton': 'സഹായം ബന്ധപ്പെടുക',
  'home.demo':'സ്മാർട്ട് ക്രോപ്പ് അഡ്വൈസറി കർഷകർക്ക് വിളവ് വർധിപ്പിക്കാൻ, അപകടസാധ്യത കുറയ്ക്കാൻ, മികച്ച തീരുമാനങ്ങൾ എടുക്കാൻ സഹായിക്കുന്ന ഒരു AI-ആധാരിത പ്ലാറ്റ്‌ഫോമാണ്. ഇത് ഇമേജ് അധിഷ്ഠിത രോഗശേഖരണം, മണ്ണ് റിപ്പോർട്ട് വിശകലനം വഴി ശരിയായ വിളകളും വളങ്ങളും നിർദേശിക്കുന്നു, കൂടാതെ ഓരോ പ്രദേശത്തിനും വ്യക്തിഗത വിള ശുപാർശകൾ നൽകുന്നു. കർഷകർക്ക് സമയബന്ധിതമായ കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ ലഭിക്കുന്നു, അതിലൂടെ വയലുകൾ സംരക്ഷിക്കാനും ജലസേചന പദ്ധതി തയ്യാറാക്കാനും കഴിയും. ഈ സംവിധാനം കർഷകർക്ക് ഓരോ വിളക്കും പ്രോജക്റ്റുകൾ സൃഷ്ടിക്കാനും പരിപാലിക്കാനും, തത്സമയ വിപണി വിലകൾ നിരീക്ഷിക്കാനും, വള പദ്ധതികൾ പിന്തുടരാനും സൗകര്യമൊരുക്കുന്നു. ഈ സവിശേഷതകൾ എല്ലാം കൂടി കർഷകർക്ക് ഉൽപാദനക്ഷമത വർധിപ്പിക്കാൻ, ചെലവ് ലാഭിക്കാൻ, മികച്ച വില നേടാൻ സഹായിക്കുന്നു.',
  'home.demobutton':'ഡെമോ കേൾക്കുക',
   'home.stopDemoVoiceButton': 'ഡെമോ നിർത്തുക',
  // Features
  'feature.soilAnalysis.title': 'മണ്ണ് വിശകലനം',
  'feature.soilAnalysis.description': 'മണ്ണ് റിപ്പോര്‍ട്ട് അപ്‌ലോഡ് ചെയ്ത് മികച്ച വിള വളര്‍ച്ചക്കും മണ്ണ് ആരോഗ്യത്തിനും AI ശുപാര്‍ശകള്‍ നേടൂ.',
  'feature.diseaseDetection.title': 'രോഗം കണ്ടെത്തല്‍',
  'feature.diseaseDetection.description': 'രോഗബാധിത വിളയുടെ ചിത്രങ്ങള്‍ എടുത്ത് AI വഴി ഉടന്‍ രോഗനിര്‍ണയവും ചികിത്സ ശുപാര്‍ശകളും നേടൂ.',
  'feature.fertilizerPlans.title': 'വള പദ്ധതി',
  'feature.fertilizerPlans.description': 'നിങ്ങളുടെ വിളയുടെ തരം, വളര്‍ച്ചാ ഘട്ടം, മണ്ണ് അവസ്ഥ എന്നിവയുടെ അടിസ്ഥാനത്തില്‍ വ്യക്തിഗത വള ഷെഡ്യൂള്‍ നേടൂ.',
  'feature.weather.title': 'വാതാവരണ മാര്‍ഗ്ഗനിര്‍ദ്ദേശം',
  'feature.weather.description': 'അനനുകൂലമായ കാലാവസ്ഥയില്‍ നിന്ന് വിളയെ സംരക്ഷിക്കാന്‍ റിയല്‍-ടൈം കാലാവസ്ഥ മുന്നറിയിപ്പുകളും കൃഷി ഉപദേശവും.',
  'feature.marketPrices.title': 'ചന്ത വില',
  'feature.marketPrices.description': 'വസ്തു വിലകള്‍ ട്രാക്ക് ചെയ്ത് ഉല്‍പന്നം വില്‍ക്കാന്‍ മികച്ച സമയത്തെക്കുറിച്ച് ബുദ്ധിമുട്ടുള്ള അറിവ് നേടൂ.',
  'feature.projects.title': 'വിള പ്രോജക്ടുകള്‍',
  'feature.projects.description': 'വ്യക്തമായ ട്രാക്കിംഗും റിപ്പോര്‍ട്ടിംഗും ഉപയോഗിച്ച് വിത്ത് മുതല്‍ വിള വരെ നിങ്ങളുടെ കൃഷി പ്രോജക്ടുകള്‍ നിയന്ത്രിക്കുക.',

  // Common
  'common.open': 'തുറക്കുക',
  'common.voice': 'ശബ്ദം',
  'common.download': 'ഡൗണ്‍ലോഡ്',
  'common.save': 'സേവ് ചെയ്യുക',
  'common.cancel': 'റദ്ദാക്കുക',
  'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
  'common.error': 'പിശക്',
  'common.success': 'വിജയം',

  // Stats
  'stats.farmersHelped': 'കർഷകര്‍ക്ക് സഹായം',
  'stats.accuracyRate': 'കൃത്യത നിരക്ക്',
  'stats.supportAvailable': 'സഹായം ലഭ്യമാണ്',

  // Soil Analysis Page
  'soil.title': 'മണ്ണ് വിശകലനം & ശുപാര്‍ശകള്‍',
  'soil.subtitle': 'AI അധിഷ്ഠിത വിശകലനത്തിനും ശുപാര്‍ശകള്‍ക്കും നിങ്ങളുടെ മണ്ണ് റിപ്പോര്‍ട്ട് അപ്‌ലോഡ് ചെയ്യുക',
  'soil.upload': 'മണ്ണ് റിപ്പോര്‍ട്ട് അപ്‌ലോഡ് ചെയ്യുക',
  'soil.analyze': 'AI ഉപയോഗിച്ച് വിശകലനം ചെയ്യുക',
  'soil.recommendations': 'AI ശുപാര്‍ശകള്‍',
  'soil.generateReport': 'റിപ്പോര്‍ട്ട് സൃഷ്ടിക്കുക',
  'soil.noFile': 'ദയവായി ആദ്യം മണ്ണ് റിപ്പോര്‍ട്ട് അപ്‌ലോഡ് ചെയ്യുക',
  'soil.analyzing': 'നിങ്ങളുടെ മണ്ണ് റിപ്പോര്‍ട്ട് വിശകലനം ചെയ്യുന്നു...',

  // Disease Detection Page
  'disease.title': 'വിള രോഗം കണ്ടെത്തല്‍',
  'disease.subtitle': 'ഉടന്‍ AI രോഗനിര്‍ണയത്തിനായി രോഗബാധിത വിളയുടെ ചിത്രങ്ങള്‍ അപ്‌ലോഡ് ചെയ്യുക',
  'disease.upload': 'വിള ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
  'disease.detect': 'രോഗം കണ്ടെത്തുക',
  'disease.diagnosis': 'രോഗനിര്‍ണയം',
  'disease.treatment': 'ചികിത്സ ശുപാര്‍ശകള്‍',
  'disease.noImage': 'ദയവായി ആദ്യം വിള ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
  'disease.detecting': 'വിള ചിത്രം വിശകലനം ചെയ്യുന്നു...',

  // Fertilizer Plans Page
  'fertilizer.title': 'വള ശുപാര്‍ശകള്‍',
  'fertilizer.subtitle': 'നിങ്ങളുടെ വിളയ്ക്ക് വ്യക്തിഗത വള പദ്ധതി നേടൂ',
  'fertilizer.selectCrop': 'വിള തരം തിരഞ്ഞെടുക്കുക',
  'fertilizer.selectStage': 'വളര്‍ച്ചാ ഘട്ടം തിരഞ്ഞെടുക്കുക',
  'fertilizer.getPlan': 'വള പദ്ധതി നേടൂ',
  'fertilizer.recommendations': 'വള ശുപാര്‍ശകള്‍',
  'fertilizer.schedule': 'അപേക്ഷ ഷെഡ്യൂള്‍',
  'fertilizer.selectBoth': 'ദയവായി വിള തരംയും വളര്‍ച്ചാ ഘട്ടവും തിരഞ്ഞെടുക്കുക',

  // Weather Page
  'weather.title': 'വാതാവരണം & കൃഷി മാര്‍ഗ്ഗനിര്‍ദ്ദേശം',
  'weather.subtitle': 'റിയല്‍-ടൈം കാലാവസ്ഥ അപ്‌ഡേറ്റുകളും കൃഷി ഉപദേശവും',
  'weather.current': 'നിലവിലെ കാലാവസ്ഥ',
  'weather.forecast': 'കാലാവസ്ഥ പ്രവചനം',
  'weather.advice': 'കൃഷി ഉപദേശം',
  'weather.alerts': 'കാലാവസ്ഥ മുന്നറിയിപ്പുകള്‍',

  // Market Prices Page
  'market.title': 'ചന്ത വില & വില്‍പ്പന മാര്‍ഗ്ഗനിര്‍ദ്ദേശം',
  'market.subtitle': 'വസ്തു വിലകള്‍ ട്രാക്ക് ചെയ്ത് വില്‍പ്പന ശുപാര്‍ശകള്‍ നേടൂ',
  'market.prices': 'നിലവിലെ ചന്ത വില',
  'market.trends': 'വില പ്രവണത',
  'market.recommendations': 'വില്‍പ്പന ശുപാര്‍ശകള്‍',
  'market.selectCrop': 'വിള തിരഞ്ഞെടുക്കുക',

  // Projects Page
  'projects.title': 'വിള പ്രോജക്ട് മാനേജ്മെന്റ്',
  'projects.subtitle': 'വിത്ത് മുതല്‍ വിള വരെ നിങ്ങളുടെ കൃഷി പ്രോജക്ടുകള്‍ നിയന്ത്രിക്കുക',
  'projects.create': 'പുതിയ പ്രോജക്ട് സൃഷ്ടിക്കുക',
  'projects.active': 'സജീവ പ്രോജക്ടുകള്‍',
  'projects.completed': 'പൂര്‍ത്തിയായ പ്രോജക്ടുകള്‍',
  'projects.view': 'പ്രോജക്ട് കാണുക',
  'projects.edit': 'പ്രോജക്ട് എഡിറ്റ് ചെയ്യുക',

  // Auth Pages
  'auth.login': 'നിങ്ങളുടെ അക്കൗണ്ടിലേക്ക് ലോഗിന്‍ ചെയ്യുക',
  'auth.signup': 'പുതിയ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
  'auth.email': 'ഇമെയില്‍ വിലാസം',
  'auth.password': 'പാസ്‌വേഡ്',
  'auth.confirmPassword': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
  'auth.name': 'പൂര്‍ണ പേര്',
  'auth.phone': 'ഫോണ്‍ നമ്പര്‍',
  'auth.loginButton': 'ലോഗിന്‍',
  'auth.signupButton': 'സൈന്‍ അപ്പ്',
  'auth.switchToSignup': 'അക്കൗണ്ട് ഇല്ലേ? സൈന്‍ അപ്പ് ചെയ്യൂ',
  'auth.switchToLogin': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ? ലോഗിന്‍ ചെയ്യൂ',
  'auth.forgotPassword': 'പാസ്‌വേഡ് മറന്നോ?',
  'auth.mobile': 'മൊബൈല്‍ നമ്പര്‍',
  'auth.location': 'സ്ഥലം',
  'auth.age': 'പ്രായം',
  'auth.enterName': 'നിങ്ങളുടെ പൂര്‍ണ പേര് നല്‍കുക',
  'auth.enterMobile': 'നിങ്ങളുടെ മൊബൈല്‍ നമ്പര്‍ നല്‍കുക',
  'auth.enterPassword': 'നിങ്ങളുടെ പാസ്‌വേഡ് നല്‍കുക',
  'auth.confirmPasswordText': 'നിങ്ങളുടെ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
  'auth.selectLocation': 'നിങ്ങളുടെ സ്ഥലം തിരഞ്ഞെടുക്കുക',
  'auth.enterAge': 'നിങ്ങളുടെ പ്രായം നല്‍കുക',
  'auth.selectFarmerType': 'കർഷക തരം തിരഞ്ഞെടുക്കുക',
  'auth.namePlaceholder': 'നിങ്ങളുടെ പൂര്‍ണ പേര് നല്‍കുക',
  'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
  'auth.passwordPlaceholder': 'ശക്തമായ പാസ്‌വേഡ് നല്‍കുക',
  'auth.confirmPasswordPlaceholder': 'പാസ്‌വേഡ് വീണ്ടും നല്‍കുക',
  'auth.agePlaceholder': 'നിങ്ങളുടെ പ്രായം നല്‍കുക',
  'auth.selectLocationPlaceholder': 'നിങ്ങളുടെ സംസ്ഥാനത്തെ തിരഞ്ഞെടുക്കുക',
  'auth.passwordMismatch': 'പാസ്‌വേഡുകള്‍ പൊരുത്തപ്പെടുന്നില്ല!',
  'auth.dontHaveAccount': 'അക്കൗണ്ട് ഇല്ലേ?',
  'auth.alreadyHaveAccount': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
  'auth.farmerType.label': 'കർഷക തരം',
  'auth.farmerType.placeholder': 'കർഷക തരം തിരഞ്ഞെടുക്കുക',
  'auth.farmerType.small': 'ചെറിയ കർഷകൻ',
  'auth.farmerType.marginal': 'അറ്റക്കാർഷകൻ',
  'auth.farmerType.business': 'വ്യവസായ കർഷകൻ',
},

or: {
  // Navigation
  'nav.home': 'ହୋମ୍',
  'nav.soilAnalysis': 'ମାଟି ବିଶ୍ଲେଷଣ',
  'nav.diseaseDetection': 'ରୋଗ ଚିହ୍ନଟ',
  'nav.fertilizerPlans': 'ସର ଯୋଜନା',
  'nav.weather': 'ପାଗ',
  'nav.marketPrices': 'ବଜାର ଦର',
  'nav.projects': 'ପ୍ରକଳ୍ପ',
  'nav.voice': 'ଶବ୍ଦ',
  'nav.login': 'ଲଗଇନ୍',

  // Home page
  'home.title': 'ସ୍ମାର୍ଟ କୃଷି',
  'home.titleAccent': 'AI ପ୍ରଯୁକ୍ତି',
  'home.subtitle': 'AI ଚାଳିତ ମାଟି ବିଶ୍ଲେଷଣ, ରୋଗ ଚିହ୍ନଟ ଏବଂ ଫସଲ ପରିଚାଳନା ସହିତ ଆପଣଙ୍କର କୃଷିକୁ ବିପ୍ଳବ କରନ୍ତୁ। ଆପଣଙ୍କର ଅଞ୍ଚଳିକ ଭାଷାରେ ଶବ୍ଦ ସହାୟତା ସହିତ ବିଶେଷଜ୍ଞ ପରାମର୍ଶ ପାଆନ୍ତୁ।',
  'home.startButton': 'ସ୍ମାର୍ଟ କୃଷି ଆରମ୍ଭ କରନ୍ତୁ',
  'home.demoButton': 'ଡେମୋ ଦେଖନ୍ତୁ',
  'home.featuresTitle': 'ସମ୍ପୂର୍ଣ୍ଣ କୃଷି ସମାଧାନ',
  'home.featuresSubtitle': 'ମାଟି ପରୀକ୍ଷାରୁ ଫସଲ ପରିଚାଳନା ପର୍ଯ୍ୟନ୍ତ, ଆମର AI ଚାଳିତ ପ୍ଲାଟଫର୍ମ ଅନେକ ଭାଷାରେ ଆଧୁନିକ କୃଷକଙ୍କୁ ବ୍ୟାପକ ସହାୟତା ଦେଇଥାଏ।',
  'home.ctaTitle': 'ଆପଣଙ୍କର କୃଷିକୁ ବଦଳାଇବାକୁ ପ୍ରସ୍ତୁତ?',
  'home.ctaSubtitle': 'ହଜାର ହଜାର କୃଷକ AI ବ୍ୟବହାର କରି ତାଙ୍କର ଫସଲ ଉତ୍ପାଦନ ଏବଂ ଲାଭ ବଢ଼ାଇଛନ୍ତି।',
  'home.trialButton': 'ମାଗଣା ଟ୍ରାୟାଲ୍ ଆରମ୍ଭ କରନ୍ତୁ',
  'home.supportButton': 'ସହାୟତା ସଂପର୍କ କରନ୍ତୁ',
  'home.demo':'"ସ୍ମାର୍ଟ କ୍ରପ୍ ଆଡଭାଇଜରୀ ଏକ AI ଭିତ୍ତିକ ପ୍ଲାଟଫର୍ମ ଯାହା କୃଷକଙ୍କୁ ଉତ୍ପାଦନ ବୃଦ୍ଧି କରିବାକୁ, ବିପଦ କମେଇବାକୁ ଏବଂ ସଠିକ୍ ସିଦ୍ଧାନ୍ତ ନେବାରେ ସହାୟତା କରେ। ଏହା ଛବି-ଆଧାରିତ ରୋଗ ସନ୍ଦେଶ, ମାଟି ରିପୋର୍ଟ ବିଶ୍ଳେଷଣ ମାଧ୍ୟମରେ ଠିକ୍ ଫସଲ ଏବଂ ସର ସୁପାରିଶ, ଏବଂ ପ୍ରତ୍ୟେକ ଅଞ୍ଚଳ ପାଇଁ ବ୍ୟକ୍ତିଗତ ଫସଲ ସୁପାରିଶ ପ୍ରଦାନ କରେ। କୃଷକମାନେ ସମୟରେ ପାଣିପାଗ ସତର୍କତା ପାଆନ୍ତି ଯାହାଦ୍ୱାରା ସେମାନେ କ୍ଷେତ୍ରକୁ ସୁରକ୍ଷିତ ରଖିପାରିବେ ଏବଂ ସିଚାଇ ପରିକଳ୍ପନା କରିପାରିବେ। ଏହି ପ୍ରଣାଳୀ କୃଷକଙ୍କୁ ପ୍ରତ୍ୟେକ ଫସଲ ପାଇଁ ପ୍ରକଳ୍ପ ସୃଷ୍ଟି କରିବା ଏବଂ ରକ୍ଷା କରିବା, ଯାଥାର୍ଥିକ ସମୟରେ ବଜାର ମୂଲ୍ୟ ଟ୍ରାକ୍ କରିବା ଏବଂ ସର ପରିକଳ୍ପନାକୁ ଅନୁସରଣ କରିବାର ସୁବିଧା ଦେଇଥାଏ। ସମସ୍ତ ସୁବିଧାଗୁଡ଼ିକ ମିଶି କୃଷକମାନଙ୍କୁ ଉତ୍ପାଦକତା ବୃଦ୍ଧି, ଖର୍ଚ୍ଚ ବଚାଇବା ଏବଂ ଭଲ ଦାମ ପାଇବାରେ ସହାୟତା କରେ।',
  'home.demobutton':'ଡେମୋ ଶୁଣନ୍ତୁ',
   'home.stopDemoVoiceButton': 'ଡେମୋ ବନ୍ଦ୍ କରନ୍ତୁ',
  // Features
  'feature.soilAnalysis.title': 'ମାଟି ବିଶ୍ଲେଷଣ',
  'feature.soilAnalysis.description': 'ମାଟି ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ ଏବଂ ଉତ୍ତମ ଫସଲ ବୃଦ୍ଧି ଏବଂ ମାଟି ସ୍ୱାସ୍ଥ୍ୟ ପାଇଁ AI ଶିଫାରସ୍ ପାଆନ୍ତୁ।',
  'feature.diseaseDetection.title': 'ରୋଗ ଚିହ୍ନଟ',
  'feature.diseaseDetection.description': 'ରୋଗଗ୍ରସ୍ତ ଫସଲର ଫଟୋ ନିଅନ୍ତୁ ଏବଂ AI ଦ୍ୱାରା ତତ୍କାଳ ଚିହ୍ନଟ ଏବଂ ଚିକିତ୍ସା ଶିଫାରସ୍ ପାଆନ୍ତୁ।',
  'feature.fertilizerPlans.title': 'ସର ଯୋଜନା',
  'feature.fertilizerPlans.description': 'ଆପଣଙ୍କର ଫସଲ ପ୍ରକାର, ବୃଦ୍ଧି ଅବସ୍ଥା ଏବଂ ମାଟି ସ୍ଥିତି ଅନୁସାରେ ବ୍ୟକ୍ତିଗତ ସର ଅନୁସୂଚୀ ପାଆନ୍ତୁ।',
  'feature.weather.title': 'ପାଗ ମାର୍ଗଦର୍ଶନ',
  'feature.weather.description': 'ଅନନୁକୂଳ ପାଗ ଅବସ୍ଥାରୁ ଫସଲକୁ ରକ୍ଷା କରିବା ପାଇଁ ରିଅଲ୍-ଟାଇମ୍ ପାଗ ଆଲର୍ଟ ଏବଂ କୃଷି ପରାମର୍ଶ।',
  'feature.marketPrices.title': 'ବଜାର ଦର',
  'feature.marketPrices.description': 'ପଣ୍ୟ ଦର ଟ୍ରାକ୍ କରନ୍ତୁ ଏବଂ ବିକ୍ରି ପାଇଁ ଉତ୍ତମ ସମୟ ବିଷୟରେ ବୁଦ୍ଧିମତ୍ତା ଅନ୍ତର୍ଦୃଷ୍ଟି ପାଆନ୍ତୁ।',
  'feature.projects.title': 'ଫସଲ ପ୍ରକଳ୍ପ',
  'feature.projects.description': 'ବିସ୍ତୃତ ଟ୍ରାକିଂ ଏବଂ ରିପୋର୍ଟିଂ ସହିତ ବିଜରୁ ଫସଲ ପର୍ଯ୍ୟନ୍ତ ଆପଣଙ୍କର କୃଷି ପ୍ରକଳ୍ପ ଚାଳନା କରନ୍ତୁ।',

  // Common
  'common.open': 'ଖୋଲନ୍ତୁ',
  'common.voice': 'ଶବ୍ଦ',
  'common.download': 'ଡାଉନଲୋଡ୍',
  'common.save': 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
  'common.cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
  'common.loading': 'ଲୋଡ୍ ହେଉଛି...',
  'common.error': 'ତ୍ରୁଟି',
  'common.success': 'ସଫଳତା',

  // Stats
  'stats.farmersHelped': 'କୃଷକଙ୍କୁ ସହାୟତା',
  'stats.accuracyRate': 'ନିଖର ହାର',
  'stats.supportAvailable': 'ସହାୟତା ଉପଲବ୍ଧ',

  // Soil Analysis Page
  'soil.title': 'ମାଟି ବିଶ୍ଲେଷଣ ଏବଂ ଶିଫାରସ୍',
  'soil.subtitle': 'AI ଆଧାରିତ ବିଶ୍ଲେଷଣ ପାଇଁ ଆପଣଙ୍କର ମାଟି ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
  'soil.upload': 'ମାଟି ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
  'soil.analyze': 'AI ସହିତ ବିଶ୍ଲେଷଣ କରନ୍ତୁ',
  'soil.recommendations': 'AI ଶିଫାରସ୍',
  'soil.generateReport': 'ରିପୋର୍ଟ ତିଆରି କରନ୍ତୁ',
  'soil.noFile': 'ଦୟାକରି ପ୍ରଥମେ ମାଟି ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
  'soil.analyzing': 'ଆପଣଙ୍କର ମାଟି ରିପୋର୍ଟ ବିଶ୍ଲେଷଣ ହେଉଛି...',

  // Disease Detection Page
  'disease.title': 'ଫସଲ ରୋଗ ଚିହ୍ନଟ',
  'disease.subtitle': 'ତତ୍କାଳ AI ଚିହ୍ନଟ ପାଇଁ ରୋଗଗ୍ରସ୍ତ ଫସଲ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ',
  'disease.upload': 'ଫସଲ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ',
  'disease.detect': 'ରୋଗ ଚିହ୍ନଟ କରନ୍ତୁ',
  'disease.diagnosis': 'ରୋଗ ନିର୍ଣ୍ଣୟ',
  'disease.treatment': 'ଚିକିତ୍ସା ଶିଫାରସ୍',
  'disease.noImage': 'ଦୟାକରି ପ୍ରଥମେ ଫସଲ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ',
  'disease.detecting': 'ଫସଲ ଫଟୋ ବିଶ୍ଲେଷଣ ହେଉଛି...',

  // Fertilizer Plans Page
  'fertilizer.title': 'ସର ଶିଫାରସ୍',
  'fertilizer.subtitle': 'ଆପଣଙ୍କର ଫସଲ ପାଇଁ ବ୍ୟକ୍ତିଗତ ସର ଯୋଜନା ପାଆନ୍ତୁ',
  'fertilizer.selectCrop': 'ଫସଲ ପ୍ରକାର ଚୟନ କରନ୍ତୁ',
  'fertilizer.selectStage': 'ବୃଦ୍ଧି ଅବସ୍ଥା ଚୟନ କରନ୍ତୁ',
  'fertilizer.getPlan': 'ସର ଯୋଜନା ପାଆନ୍ତୁ',
  'fertilizer.recommendations': 'ସର ଶିଫାରସ୍',
  'fertilizer.schedule': 'ଅନୁସୂଚୀ',
  'fertilizer.selectBoth': 'ଦୟାକରି ଫସଲ ପ୍ରକାର ଏବଂ ବୃଦ୍ଧି ଅବସ୍ଥା ଦୁହିଁ ଚୟନ କରନ୍ତୁ',

  // Weather Page
  'weather.title': 'ପାଗ ଏବଂ କୃଷି ମାର୍ଗଦର୍ଶନ',
  'weather.subtitle': 'ରିଅଲ୍-ଟାଇମ୍ ପାଗ ଅପଡେଟ୍ ଏବଂ କୃଷି ପରାମର୍ଶ',
  'weather.current': 'ବର୍ତ୍ତମାନ ପାଗ',
  'weather.forecast': 'ପାଗ ପୂର୍ବାନୁମାନ',
  'weather.advice': 'କୃଷି ପରାମର୍ଶ',
  'weather.alerts': 'ପାଗ ଆଲର୍ଟ',

  // Market Prices Page
  'market.title': 'ବଜାର ଦର ଏବଂ ବିକ୍ରି ମାର୍ଗଦର୍ଶନ',
  'market.subtitle': 'ପଣ୍ୟ ଦର ଟ୍ରାକ୍ କରନ୍ତୁ ଏବଂ ବିକ୍ରି ଶିଫାରସ୍ ପାଆନ୍ତୁ',
  'market.prices': 'ବର୍ତ୍ତମାନ ବଜାର ଦର',
  'market.trends': 'ଦର ପ୍ରବୃତ୍ତି',
  'market.recommendations': 'ବିକ୍ରି ଶିଫାରସ୍',
  'market.selectCrop': 'ଫସଲ ଚୟନ କରନ୍ତୁ',

  // Projects Page
  'projects.title': 'ଫସଲ ପ୍ରକଳ୍ପ ପରିଚାଳନା',
  'projects.subtitle': 'ବିଜରୁ ଫସଲ ପର୍ଯ୍ୟନ୍ତ ଆପଣଙ୍କର କୃଷି ପ୍ରକଳ୍ପ ଚାଳନା କରନ୍ତୁ',
  'projects.create': 'ନୂତନ ପ୍ରକଳ୍ପ ତିଆରି କରନ୍ତୁ',
  'projects.active': 'ସକ୍ରିୟ ପ୍ରକଳ୍ପ',
  'projects.completed': 'ସମ୍ପୂର୍ଣ୍ଣ ପ୍ରକଳ୍ପ',
  'projects.view': 'ପ୍ରକଳ୍ପ ଦେଖନ୍ତୁ',
  'projects.edit': 'ପ୍ରକଳ୍ପ ସମ୍ପାଦନ କରନ୍ତୁ',

  // Auth Pages
  'auth.login': 'ଆପଣଙ୍କର ଖାତାକୁ ଲଗଇନ୍ କରନ୍ତୁ',
  'auth.signup': 'ନୂତନ ଖାତା ତିଆରି କରନ୍ତୁ',
  'auth.email': 'ଇମେଲ୍ ଠିକଣା',
  'auth.password': 'ପାସୱାର୍ଡ',
  'auth.confirmPassword': 'ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ',
  'auth.name': 'ପୂର୍ଣ୍ଣ ନାମ',
  'auth.phone': 'ଫୋନ୍ ନମ୍ବର',
  'auth.loginButton': 'ଲଗଇନ୍',
  'auth.signupButton': 'ସାଇନ୍ ଅପ୍',
  'auth.switchToSignup': 'ଖାତା ନାହିଁ? ସାଇନ୍ ଅପ୍ କରନ୍ତୁ',
  'auth.switchToLogin': 'ପୂର୍ବରୁ ଖାତା ଅଛି? ଲଗଇନ୍ କରନ୍ତୁ',
  'auth.forgotPassword': 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ?',
  'auth.mobile': 'ମୋବାଇଲ୍ ନମ୍ବର',
  'auth.location': 'ଅବସ୍ଥାନ',
  'auth.age': 'ବୟସ୍',
  'auth.enterName': 'ଆପଣଙ୍କର ପୂର୍ଣ୍ଣ ନାମ ଦିଅନ୍ତୁ',
  'auth.enterMobile': 'ଆପଣଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ',
  'auth.enterPassword': 'ଆପଣଙ୍କର ପାସୱାର୍ଡ ଦିଅନ୍ତୁ',
  'auth.confirmPasswordText': 'ଆପଣଙ୍କର ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ',
  'auth.selectLocation': 'ଆପଣଙ୍କର ଅବସ୍ଥାନ ଚୟନ କରନ୍ତୁ',
  'auth.enterAge': 'ଆପଣଙ୍କର ବୟସ୍ ଦିଅନ୍ତୁ',
  'auth.selectFarmerType': 'କୃଷକ ପ୍ରକାର ଚୟନ କରନ୍ତୁ',
  'auth.namePlaceholder': 'ଆପଣଙ୍କର ପୂର୍ଣ୍ଣ ନାମ ଦିଅନ୍ତୁ',
  'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
  'auth.passwordPlaceholder': 'ଶକ୍ତିଶାଳୀ ପାସୱାର୍ଡ ଦିଅନ୍ତୁ',
  'auth.confirmPasswordPlaceholder': 'ପାସୱାର୍ଡ ପୁଣି ଦିଅନ୍ତୁ',
  'auth.agePlaceholder': 'ଆପଣଙ୍କର ବୟସ୍ ଦିଅନ୍ତୁ',
  'auth.selectLocationPlaceholder': 'ଆପଣଙ୍କର ରାଜ୍ୟ ଚୟନ କରନ୍ତୁ',
  'auth.passwordMismatch': 'ପାସୱାର୍ଡ ମେଳ ଖାଉନାହିଁ!',
  'auth.dontHaveAccount': 'ଖାତା ନାହିଁ?',
  'auth.alreadyHaveAccount': 'ପୂର୍ବରୁ ଖାତା ଅଛି?',
  'auth.farmerType.label': 'କୃଷକ ପ୍ରକାର',
  'auth.farmerType.placeholder': 'କୃଷକ ପ୍ରକାର ଚୟନ କରନ୍ତୁ',
  'auth.farmerType.small': 'ଛୋଟ କୃଷକ',
  'auth.farmerType.marginal': 'ସୀମାନ୍ତ କୃଷକ',
  'auth.farmerType.business': 'ବ୍ୟବସାୟୀ କୃଷକ',
},

pa: {
  // Navigation
  'nav.home': 'ਹੋਮ',
  'nav.soilAnalysis': 'ਮਿੱਟੀ ਵਿਸ਼ਲੇਸ਼ਣ',
  'nav.diseaseDetection': 'ਬਿਮਾਰੀ ਪਛਾਣ',
  'nav.fertilizerPlans': 'ਖਾਦ ਯੋਜਨਾ',
  'nav.weather': 'ਮੌਸਮ',
  'nav.marketPrices': 'ਬਾਜ਼ਾਰ ਭਾਵ',
  'nav.projects': 'ਪ੍ਰੋਜੈਕਟ',
  'nav.voice': 'ਆਵਾਜ਼',
  'nav.login': 'ਲੌਗਇਨ',

  // Home page
  'home.title': 'ਸਮਾਰਟ ਖੇਤੀ',
  'home.titleAccent': 'AI ਤਕਨਾਲੋਜੀ',
  'home.subtitle': 'AI-ਚਲਿਤ ਮਿੱਟੀ ਵਿਸ਼ਲੇਸ਼ਣ, ਬਿਮਾਰੀ ਪਛਾਣ ਅਤੇ ਫ਼ਸਲ ਪ੍ਰਬੰਧਨ ਨਾਲ ਆਪਣੀ ਖੇਤੀ ਵਿੱਚ ਇਨਕਲਾਬ ਲਿਆਓ। ਆਪਣੀ ਸਥਾਨਕ ਭਾਸ਼ਾ ਵਿੱਚ ਆਵਾਜ਼ ਸਹਾਇਤਾ ਨਾਲ ਵਿਸ਼ੇਸ਼ਗਿਆਨ ਸਲਾਹ ਲਵੋ।',
  'home.startButton': 'ਸਮਾਰਟ ਖੇਤੀ ਸ਼ੁਰੂ ਕਰੋ',
  'home.demoButton': 'ਡੈਮੋ ਵੇਖੋ',
  'home.featuresTitle': 'ਪੂਰਾ ਖੇਤੀ ਹੱਲ',
  'home.featuresSubtitle': 'ਮਿੱਟੀ ਜਾਂਚ ਤੋਂ ਫ਼ਸਲ ਪ੍ਰਬੰਧਨ ਤੱਕ, ਸਾਡਾ AI-ਚਲਿਤ ਪਲੇਟਫਾਰਮ ਕਈ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਆਧੁਨਿਕ ਕਿਸਾਨਾਂ ਲਈ ਵਿਸ਼ਤ੍ਰਿਤ ਸਹਾਇਤਾ ਦਿੰਦਾ ਹੈ।',
  'home.ctaTitle': 'ਆਪਣੀ ਖੇਤੀ ਬਦਲਣ ਲਈ ਤਿਆਰ ਹੋ?',
  'home.ctaSubtitle': 'ਹਜ਼ਾਰਾਂ ਕਿਸਾਨ ਪਹਿਲਾਂ ਹੀ AI ਵਰਤ ਕੇ ਆਪਣੀ ਫ਼ਸਲ ਦੀ ਪੈਦਾਵਾਰ ਅਤੇ ਨਫ਼ਾ ਵਧਾ ਰਹੇ ਹਨ।',
  'home.trialButton': 'ਮੁਫ਼ਤ ਟ੍ਰਾਇਲ ਸ਼ੁਰੂ ਕਰੋ',
  'home.supportButton': 'ਸਹਾਇਤਾ ਸੰਪਰਕ ਕਰੋ',
  'home.demo':'ਸਮਾਰਟ ਕ੍ਰਾਪ ਐਡਵਾਈਜ਼ਰੀ ਇੱਕ AI-ਆਧਾਰਤ ਪਲੇਟਫਾਰਮ ਹੈ ਜੋ ਕਿਸਾਨਾਂ ਨੂੰ ਪੈਦਾਵਾਰ ਵਧਾਉਣ, ਜੋਖਮ ਘਟਾਉਣ ਅਤੇ ਵਧੀਆ ਫੈਸਲੇ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ। ਇਹ ਚਿੱਤਰ-ਆਧਾਰਤ ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ, ਮਿੱਟੀ ਦੀ ਰਿਪੋਰਟ ਵਿਸ਼ਲੇਸ਼ਣ ਰਾਹੀਂ ਸਹੀ ਫਸਲਾਂ ਅਤੇ ਖਾਦ ਦੀ ਸਿਫਾਰਸ਼ ਕਰਦਾ ਹੈ, ਅਤੇ ਹਰ ਖੇਤਰ ਲਈ ਨਿੱਜੀ ਫਸਲਾਂ ਦੀ ਸਿਫਾਰਸ਼ ਦਿੰਦਾ ਹੈ। ਕਿਸਾਨਾਂ ਨੂੰ ਸਮੇਂ-ਸਿਰ ਮੌਸਮ ਚੇਤਾਵਨੀਆਂ ਵੀ ਮਿਲਦੀਆਂ ਹਨ, ਜਿਸ ਨਾਲ ਉਹ ਖੇਤਾਂ ਦੀ ਰੱਖਿਆ ਕਰ ਸਕਦੇ ਹਨ ਅਤੇ ਸਿੰਚਾਈ ਦੀ ਯੋਜਨਾ ਬਣਾ ਸਕਦੇ ਹਨ। ਇਹ ਸਿਸਟਮ ਕਿਸਾਨਾਂ ਨੂੰ ਹਰ ਫਸਲ ਲਈ ਪ੍ਰੋਜੈਕਟ ਬਣਾਉਣ ਅਤੇ ਰੱਖਣ, ਰੀਅਲ-ਟਾਈਮ ਵਿੱਚ ਬਾਜ਼ਾਰ ਕੀਮਤਾਂ ਟਰੈਕ ਕਰਨ ਅਤੇ ਖਾਦ ਦੀ ਯੋਜਨਾ ਦੀ ਪਾਲਣਾ ਕਰਨ ਦੀ ਸਹੂਲਤ ਦਿੰਦਾ ਹੈ। ਇਹ ਸਾਰੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਮਿਲ ਕੇ ਕਿਸਾਨਾਂ ਨੂੰ ਉਤਪਾਦਕਤਾ ਵਧਾਉਣ, ਖਰਚੇ ਘਟਾਉਣ ਅਤੇ ਵਧੀਆ ਕੀਮਤਾਂ ਪ੍ਰਾਪਤ ਕਰਨ ਵਿੱਚ ਸਮਰੱਥ ਬਣਾਉਂਦੀਆਂ ਹਨ।',
  'home.demobutton':'ਡੈਮੋ ਸੁਣੋ',
   'home.stopDemoVoiceButton': 'ਡੈਮੋ ਬੰਦ ਕਰੋ',
  // Features
  'feature.soilAnalysis.title': 'ਮਿੱਟੀ ਵਿਸ਼ਲੇਸ਼ਣ',
  'feature.soilAnalysis.description': 'ਮਿੱਟੀ ਦੀ ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ ਅਤੇ ਵਧੀਆ ਫ਼ਸਲ ਵਾਧੂ ਅਤੇ ਮਿੱਟੀ ਸਿਹਤ ਲਈ AI-ਚਲਿਤ ਸਿਫਾਰਸ਼ਾਂ ਲਵੋ।',
  'feature.diseaseDetection.title': 'ਬਿਮਾਰੀ ਪਛਾਣ',
  'feature.diseaseDetection.description': 'ਬਿਮਾਰ ਫ਼ਸਲਾਂ ਦੀਆਂ ਤਸਵੀਰਾਂ ਲਵੋ ਅਤੇ ਸਾਡੀ AI ਤੋਂ ਤੁਰੰਤ ਨਿਦਾਨ ਅਤੇ ਇਲਾਜ ਦੀ ਸਿਫਾਰਸ਼ ਲਵੋ।',
  'feature.fertilizerPlans.title': 'ਖਾਦ ਯੋਜਨਾ',
  'feature.fertilizerPlans.description': 'ਆਪਣੀ ਫ਼ਸਲ ਦੀ ਕਿਸਮ, ਵਾਧੂ ਪੜਾਅ ਅਤੇ ਮਿੱਟੀ ਦੀ ਹਾਲਤ ਦੇ ਆਧਾਰ ਤੇ ਨਿੱਜੀ ਖਾਦ ਸ਼ਡਿਊਲ ਲਵੋ।',
  'feature.weather.title': 'ਮੌਸਮ ਮਾਰਗਦਰਸ਼ਨ',
  'feature.weather.description': 'ਅਨੁਕੂਲ ਮੌਸਮ ਤੋਂ ਫ਼ਸਲਾਂ ਦੀ ਰੱਖਿਆ ਲਈ ਰੀਅਲ-ਟਾਈਮ ਮੌਸਮ ਚੇਤਾਵਨੀ ਅਤੇ ਖੇਤੀ ਸਲਾਹ।',
  'feature.marketPrices.title': 'ਬਾਜ਼ਾਰ ਭਾਵ',
  'feature.marketPrices.description': 'ਵਸਤੂਆਂ ਦੇ ਭਾਵ ਟ੍ਰੈਕ ਕਰੋ ਅਤੇ ਵਿਕਰੀ ਲਈ ਵਧੀਆ ਸਮੇਂ ਬਾਰੇ ਸਮਝ ਲਵੋ।',
  'feature.projects.title': 'ਫ਼ਸਲ ਪ੍ਰੋਜੈਕਟ',
  'feature.projects.description': 'ਵਿਸ਼ਤ੍ਰਿਤ ਟ੍ਰੈਕਿੰਗ ਅਤੇ ਰਿਪੋਰਟਿੰਗ ਨਾਲ ਬੀਜ ਤੋਂ ਫ਼ਸਲ ਤੱਕ ਆਪਣੀ ਖੇਤੀ ਪ੍ਰੋਜੈਕਟਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ।',

  // Common
  'common.open': 'ਖੋਲੋ',
  'common.voice': 'ਆਵਾਜ਼',
  'common.download': 'ਡਾਊਨਲੋਡ',
  'common.save': 'ਸੰਭਾਲੋ',
  'common.cancel': 'ਰੱਦ ਕਰੋ',
  'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
  'common.error': 'ਗਲਤੀ',
  'common.success': 'ਸਫਲਤਾ',

  // Stats
  'stats.farmersHelped': 'ਕਿਸਾਨਾਂ ਦੀ ਮਦਦ ਕੀਤੀ',
  'stats.accuracyRate': 'ਸ਼ੁੱਧਤਾ ਦਰ',
  'stats.supportAvailable': 'ਸਹਾਇਤਾ ਉਪਲਬਧ',

  // Soil Analysis Page
  'soil.title': 'ਮਿੱਟੀ ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਸਿਫਾਰਸ਼ਾਂ',
  'soil.subtitle': 'AI-ਚਲਿਤ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਆਪਣੀ ਮਿੱਟੀ ਦੀ ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ',
  'soil.upload': 'ਮਿੱਟੀ ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ',
  'soil.analyze': 'AI ਨਾਲ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
  'soil.recommendations': 'AI ਸਿਫਾਰਸ਼ਾਂ',
  'soil.generateReport': 'ਰਿਪੋਰਟ ਬਣਾਓ',
  'soil.noFile': 'ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਮਿੱਟੀ ਦੀ ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ',
  'soil.analyzing': 'ਤੁਹਾਡੀ ਮਿੱਟੀ ਦੀ ਰਿਪੋਰਟ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਹੀ ਹੈ...',

  // Disease Detection Page
  'disease.title': 'ਫ਼ਸਲ ਬਿਮਾਰੀ ਪਛਾਣ',
  'disease.subtitle': 'ਤੁਰੰਤ AI ਨਿਦਾਨ ਲਈ ਬਿਮਾਰ ਫ਼ਸਲ ਦੀ ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ',
  'disease.upload': 'ਫ਼ਸਲ ਦੀ ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ',
  'disease.detect': 'ਬਿਮਾਰੀ ਪਛਾਣੋ',
  'disease.diagnosis': 'ਬਿਮਾਰੀ ਨਿਦਾਨ',
  'disease.treatment': 'ਇਲਾਜ ਦੀ ਸਿਫਾਰਸ਼',
  'disease.noImage': 'ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਫ਼ਸਲ ਦੀ ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ',
  'disease.detecting': 'ਫ਼ਸਲ ਦੀ ਤਸਵੀਰ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਹੀ ਹੈ...',

  // Fertilizer Plans Page
  'fertilizer.title': 'ਖਾਦ ਸਿਫਾਰਸ਼ਾਂ',
  'fertilizer.subtitle': 'ਆਪਣੀ ਫ਼ਸਲਾਂ ਲਈ ਨਿੱਜੀ ਖਾਦ ਯੋਜਨਾ ਲਵੋ',
  'fertilizer.selectCrop': 'ਫ਼ਸਲ ਦੀ ਕਿਸਮ ਚੁਣੋ',
  'fertilizer.selectStage': 'ਵਾਧੂ ਪੜਾਅ ਚੁਣੋ',
  'fertilizer.getPlan': 'ਖਾਦ ਯੋਜਨਾ ਲਵੋ',
  'fertilizer.recommendations': 'ਖਾਦ ਸਿਫਾਰਸ਼ਾਂ',
  'fertilizer.schedule': 'ਅਰਜ਼ੀ ਸ਼ਡਿਊਲ',
  'fertilizer.selectBoth': 'ਕਿਰਪਾ ਕਰਕੇ ਫ਼ਸਲ ਦੀ ਕਿਸਮ ਅਤੇ ਵਾਧੂ ਪੜਾਅ ਦੋਵੇਂ ਚੁਣੋ',

  // Weather Page
  'weather.title': 'ਮੌਸਮ ਅਤੇ ਖੇਤੀ ਮਾਰਗਦਰਸ਼ਨ',
  'weather.subtitle': 'ਰੀਅਲ-ਟਾਈਮ ਮੌਸਮ ਅੱਪਡੇਟ ਅਤੇ ਖੇਤੀ ਸਲਾਹ',
  'weather.current': 'ਮੌਜੂਦਾ ਮੌਸਮ',
  'weather.forecast': 'ਮੌਸਮ ਪੂਰਵਾਨੁਮਾਨ',
  'weather.advice': 'ਖੇਤੀ ਸਲਾਹ',
  'weather.alerts': 'ਮੌਸਮ ਚੇਤਾਵਨੀ',

  // Market Prices Page
  'market.title': 'ਬਾਜ਼ਾਰ ਭਾਵ ਅਤੇ ਵਿਕਰੀ ਮਾਰਗਦਰਸ਼ਨ',
  'market.subtitle': 'ਵਸਤੂਆਂ ਦੇ ਭਾਵ ਟ੍ਰੈਕ ਕਰੋ ਅਤੇ ਵਿਕਰੀ ਸਿਫਾਰਸ਼ਾਂ ਲਵੋ',
  'market.prices': 'ਮੌਜੂਦਾ ਬਾਜ਼ਾਰ ਭਾਵ',
  'market.trends': 'ਭਾਵ ਦੀ ਰੁਝਾਨ',
  'market.recommendations': 'ਵਿਕਰੀ ਸਿਫਾਰਸ਼ਾਂ',
  'market.selectCrop': 'ਫ਼ਸਲ ਚੁਣੋ',

  // Projects Page
  'projects.title': 'ਫ਼ਸਲ ਪ੍ਰੋਜੈਕਟ ਪ੍ਰਬੰਧਨ',
  'projects.subtitle': 'ਬੀਜ ਤੋਂ ਫ਼ਸਲ ਤੱਕ ਆਪਣੀ ਖੇਤੀ ਪ੍ਰੋਜੈਕਟਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
  'projects.create': 'ਨਵਾਂ ਪ੍ਰੋਜੈਕਟ ਬਣਾਓ',
  'projects.active': 'ਸਕਰੀਅ ਪ੍ਰੋਜੈਕਟ',
  'projects.completed': 'ਪੂਰੇ ਹੋਏ ਪ੍ਰੋਜੈਕਟ',
  'projects.view': 'ਪ੍ਰੋਜੈਕਟ ਵੇਖੋ',
  'projects.edit': 'ਪ੍ਰੋਜੈਕਟ ਸੰਪਾਦਿਤ ਕਰੋ',

  // Auth Pages
  'auth.login': 'ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਲੌਗਇਨ ਕਰੋ',
  'auth.signup': 'ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ',
  'auth.email': 'ਈਮੇਲ ਐਡਰੈੱਸ',
  'auth.password': 'ਪਾਸਵਰਡ',
  'auth.confirmPassword': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
  'auth.name': 'ਪੂਰਾ ਨਾਮ',
  'auth.phone': 'ਫ਼ੋਨ ਨੰਬਰ',
  'auth.loginButton': 'ਲੌਗਇਨ',
  'auth.signupButton': 'ਸਾਈਨ ਅੱਪ',
  'auth.switchToSignup': 'ਖਾਤਾ ਨਹੀਂ ਹੈ? ਸਾਈਨ ਅੱਪ ਕਰੋ',
  'auth.switchToLogin': 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ? ਲੌਗਇਨ ਕਰੋ',
  'auth.forgotPassword': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
  'auth.mobile': 'ਮੋਬਾਈਲ ਨੰਬਰ',
  'auth.location': 'ਟਿਕਾਣਾ',
  'auth.age': 'ਉਮਰ',
  'auth.enterName': 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ',
  'auth.enterMobile': 'ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
  'auth.enterPassword': 'ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
  'auth.confirmPasswordText': 'ਆਪਣੇ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
  'auth.selectLocation': 'ਆਪਣਾ ਟਿਕਾਣਾ ਚੁਣੋ',
  'auth.enterAge': 'ਆਪਣੀ ਉਮਰ ਦਰਜ ਕਰੋ',
  'auth.selectFarmerType': 'ਕਿਸਾਨ ਦੀ ਕਿਸਮ ਚੁਣੋ',
  'auth.namePlaceholder': 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ',
  'auth.mobilePlaceholder': '+91 XXXXX XXXXX',
  'auth.passwordPlaceholder': 'ਮਜ਼ਬੂਤ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
  'auth.confirmPasswordPlaceholder': 'ਪਾਸਵਰਡ ਫਿਰ ਦਰਜ ਕਰੋ',
  'auth.agePlaceholder': 'ਆਪਣੀ ਉਮਰ ਦਰਜ ਕਰੋ',
  'auth.selectLocationPlaceholder': 'ਆਪਣਾ ਰਾਜ ਚੁਣੋ',
  'auth.passwordMismatch': 'ਪਾਸਵਰਡ ਮਿਲਦੇ ਨਹੀਂ!',
  'auth.dontHaveAccount': 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
  'auth.alreadyHaveAccount': 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?',
  'auth.farmerType.label': 'ਕਿਸਾਨ ਦੀ ਕਿਸਮ',
  'auth.farmerType.placeholder': 'ਕਿਸਾਨ ਦੀ ਕਿਸਮ ਚੁਣੋ',
  'auth.farmerType.small': 'ਛੋਟਾ ਕਿਸਾਨ',
  'auth.farmerType.marginal': 'ਸੀਮਾਂਤ ਕਿਸਾਨ',
  'auth.farmerType.business': 'ਵਪਾਰੀ ਕਿਸਾਨ',
},
  
}